import { Quote } from '../types';

export const bengaliQuotes: Quote[] = [
  // ===== বেগম রোকেয়া সাখাওয়াত হোসেন (Begum Rokeya) =====
  {
    text: "আমাদিগকে অন্ধকারে রাখিবার জন্য পুরুষগণ ঐ ধর্মগ্রন্থগুলিকে ঢালরূপে ব্যবহার করিতেছে।",
    author: "Begum Rokeya Sakhawat Hossain",
    role: "Writer, Educator & Social Activist",
    imageUrl: "",
    gradient: "from-emerald-400 to-teal-600",
    emoji: "📖",
  },
  {
    text: "জ্ঞান অর্জন করা মুসলমান নর-নারী সকলের জন্য ফরজ।",
    author: "Begum Rokeya Sakhawat Hossain",
    role: "Writer, Educator & Social Activist",
    imageUrl: "",
    gradient: "from-violet-400 to-purple-600",
    emoji: "✍️",
  },
  {
    text: "আমরা সমাজের অর্ধাঙ্গ, আমরা পড়িয়া থাকিলে সমাজ কিরূপে উঠিবে?",
    author: "Begum Rokeya Sakhawat Hossain",
    role: "Writer, Educator & Social Activist",
    imageUrl: "",
    gradient: "from-rose-400 to-red-600",
    emoji: "🪷",
  },
  {
    text: "তোমরা নিজে মরো, তবু অন্যায়ের কাছে মাথা নত করো না।",
    author: "Begum Rokeya Sakhawat Hossain",
    role: "Writer, Educator & Social Activist",
    imageUrl: "",
    gradient: "from-amber-400 to-orange-500",
    emoji: "🔥",
  },
  {
    text: "পুরুষদের স্বার্থেই নারীদের জাগিতে হইবে।",
    author: "Begum Rokeya Sakhawat Hossain",
    role: "Writer, Educator & Social Activist",
    imageUrl: "",
    gradient: "from-sky-400 to-blue-600",
    emoji: "✊",
  },
  {
    text: "মেয়েদের এমন শিক্ষায় শিক্ষিত করিতে হইবে যাহাতে তাহারা ভবিষ্যতে সুগৃহিণী, সুমাতা এবং সুনাগরিক হইতে পারে।",
    author: "Begum Rokeya Sakhawat Hossain",
    role: "Writer, Educator & Social Activist",
    imageUrl: "",
    gradient: "from-teal-400 to-emerald-600",
    emoji: "🎓",
  },
  {
    text: "স্ত্রীজাতির উন্নতি না হইলে দেশের উন্নতি অসম্ভব।",
    author: "Begum Rokeya Sakhawat Hossain",
    role: "Writer, Educator & Social Activist",
    imageUrl: "",
    gradient: "from-pink-400 to-rose-600",
    emoji: "🪷",
  },
  {
    text: "আমরা পুরুষদের দাসী নই — আমরা তাহাদের সঙ্গিনী।",
    author: "Begum Rokeya Sakhawat Hossain",
    role: "Writer, Educator & Social Activist",
    imageUrl: "",
    gradient: "from-indigo-400 to-violet-700",
    emoji: "💪",
  },
  {
    text: "নারী-পুরুষ কেহ কাহারো শত্রু নহে, পরস্পর পরস্পরের সহযোগী।",
    author: "Begum Rokeya Sakhawat Hossain",
    role: "Writer, Educator & Social Activist",
    imageUrl: "",
    gradient: "from-fuchsia-500 to-purple-700",
    emoji: "🤝",
  },
  {
    text: "উন্নতি করিতে হইলে ঐক্যবদ্ধ হও।",
    author: "Begum Rokeya Sakhawat Hossain",
    role: "Writer, Educator & Social Activist",
    imageUrl: "",
    gradient: "from-cyan-400 to-teal-600",
    emoji: "🕊️",
  },

  // ===== আশাপূর্ণা দেবী (Ashapurna Devi) =====
  {
    text: "নারীর জীবনে সবচেয়ে বড় শক্তি হলো তার আত্মসম্মানবোধ।",
    author: "Ashapurna Devi",
    role: "Novelist & Jnanpith Award Winner",
    imageUrl: "",
    gradient: "from-amber-300 to-yellow-600",
    emoji: "📚",
  },
  {
    text: "মানুষের ভেতরের মানুষটাকে চেনা সবচেয়ে কঠিন।",
    author: "Ashapurna Devi",
    role: "Novelist & Jnanpith Award Winner",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "✍️",
  },
  {
    text: "সত্যি কথা বলতে গেলে বিপদ আসে, না বলতে গেলে বিবেক কাঁদে।",
    author: "Ashapurna Devi",
    role: "Novelist & Jnanpith Award Winner",
    imageUrl: "",
    gradient: "from-blue-400 to-indigo-600",
    emoji: "📖",
  },
  {
    text: "শিক্ষা মানুষের তৃতীয় চোখ।",
    author: "Ashapurna Devi",
    role: "Novelist & Jnanpith Award Winner",
    imageUrl: "",
    gradient: "from-red-400 to-pink-600",
    emoji: "👁️",
  },
  {
    text: "প্রত্যেকটা মানুষের ভেতরে একটা নিজস্ব জগৎ থাকে — সেই জগতের রাজা সে নিজেই।",
    author: "Ashapurna Devi",
    role: "Novelist & Jnanpith Award Winner",
    imageUrl: "",
    gradient: "from-orange-400 to-red-500",
    emoji: "🌍",
  },
  {
    text: "মেয়েদের লড়াইটা ঘরে থেকেই শুরু হয়।",
    author: "Ashapurna Devi",
    role: "Novelist & Jnanpith Award Winner",
    imageUrl: "",
    gradient: "from-violet-400 to-purple-600",
    emoji: "🏠",
  },
  {
    text: "নিজেকে চেনো, তারপর পৃথিবীকে চেনার চেষ্টা করো।",
    author: "Ashapurna Devi",
    role: "Novelist & Jnanpith Award Winner",
    imageUrl: "",
    gradient: "from-lime-400 to-green-600",
    emoji: "🪞",
  },
  {
    text: "যে মেয়ে নিজের পায়ে দাঁড়াতে পারে না, সে কোনোদিন মাথা উঁচু করে দাঁড়াতে পারবে না।",
    author: "Ashapurna Devi",
    role: "Novelist & Jnanpith Award Winner",
    imageUrl: "",
    gradient: "from-rose-400 to-red-600",
    emoji: "🪷",
  },
  {
    text: "জীবন একটা প্রবাহ, থেমে গেলে সেটা আর জীবন থাকে না।",
    author: "Ashapurna Devi",
    role: "Novelist & Jnanpith Award Winner",
    imageUrl: "",
    gradient: "from-sky-400 to-blue-600",
    emoji: "🌊",
  },
  {
    text: "একটা ছোট্ট মেয়ের স্বপ্নের মধ্যে একটা গোটা পৃথিবী লুকিয়ে থাকে।",
    author: "Ashapurna Devi",
    role: "Novelist & Jnanpith Award Winner",
    imageUrl: "",
    gradient: "from-purple-400 to-fuchsia-600",
    emoji: "🌟",
  },

  // ===== মহাশ্বেতা দেবী (Mahasweta Devi) =====
  {
    text: "লেখকের কোনো অবসর নেই — যতদিন অন্যায় আছে, ততদিন লিখে যেতে হবে।",
    author: "Mahasweta Devi",
    role: "Writer, Activist & Magsaysay Award Winner",
    imageUrl: "",
    gradient: "from-red-400 to-pink-600",
    emoji: "✍️",
  },
  {
    text: "আদিবাসীদের অধিকারের জন্য লড়াই করাটা আমার জীবনের ব্রত।",
    author: "Mahasweta Devi",
    role: "Writer, Activist & Magsaysay Award Winner",
    imageUrl: "",
    gradient: "from-emerald-400 to-teal-600",
    emoji: "✊",
  },
  {
    text: "আমি লেখা দিয়ে প্রতিবাদ করি, কারণ কলমই আমার অস্ত্র।",
    author: "Mahasweta Devi",
    role: "Writer, Activist & Magsaysay Award Winner",
    imageUrl: "",
    gradient: "from-amber-400 to-orange-500",
    emoji: "🖊️",
  },
  {
    text: "গরিবের কোনো ইতিহাস নেই — তাদের ইতিহাস লেখার দায়িত্ব আমাদের।",
    author: "Mahasweta Devi",
    role: "Writer, Activist & Magsaysay Award Winner",
    imageUrl: "",
    gradient: "from-slate-400 to-gray-700",
    emoji: "📜",
  },
  {
    text: "সাহিত্য সমাজের আয়না — সেই আয়নায় সত্যকে দেখাতে হবে।",
    author: "Mahasweta Devi",
    role: "Writer, Activist & Magsaysay Award Winner",
    imageUrl: "",
    gradient: "from-blue-400 to-indigo-600",
    emoji: "🪞",
  },
  {
    text: "প্রতিটা মানুষের বেঁচে থাকার অধিকার সমান।",
    author: "Mahasweta Devi",
    role: "Writer, Activist & Magsaysay Award Winner",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "⚖️",
  },
  {
    text: "অন্যায়ের বিরুদ্ধে নীরব থাকাটাও একটা অন্যায়।",
    author: "Mahasweta Devi",
    role: "Writer, Activist & Magsaysay Award Winner",
    imageUrl: "",
    gradient: "from-rose-400 to-red-600",
    emoji: "🔥",
  },
  {
    text: "মানুষের পাশে দাঁড়ানোই জীবনের সবচেয়ে বড় ধর্ম।",
    author: "Mahasweta Devi",
    role: "Writer, Activist & Magsaysay Award Winner",
    imageUrl: "",
    gradient: "from-indigo-400 to-violet-700",
    emoji: "🤝",
  },
  {
    text: "শোষিতের কান্না শুনতে পাওয়াটাই সবচেয়ে কঠিন কাজ।",
    author: "Mahasweta Devi",
    role: "Writer, Activist & Magsaysay Award Winner",
    imageUrl: "",
    gradient: "from-teal-400 to-emerald-600",
    emoji: "👂",
  },
  {
    text: "ইতিহাসকে প্রশ্ন করো — কার ইতিহাস লেখা হচ্ছে, কার ইতিহাস চাপা পড়ছে।",
    author: "Mahasweta Devi",
    role: "Writer, Activist & Magsaysay Award Winner",
    imageUrl: "",
    gradient: "from-fuchsia-500 to-purple-700",
    emoji: "❓",
  },

  // ===== কামিনী রায় (Kamini Roy) =====
  {
    text: "করিতে পারি না কাজ, সদা ভয় সদা লাজ, সংশয়ে সংকল্প সদা টলে।",
    author: "Kamini Roy",
    role: "Poet & First Female Honours Graduate of British India",
    imageUrl: "",
    gradient: "from-pink-400 to-rose-600",
    emoji: "🪷",
  },
  {
    text: "সকলের তরে সকলে আমরা, প্রত্যেকে আমরা পরের তরে।",
    author: "Kamini Roy",
    role: "Poet & First Female Honours Graduate of British India",
    imageUrl: "",
    gradient: "from-violet-400 to-purple-600",
    emoji: "🕊️",
  },
  {
    text: "পাছে লোকে কিছু বলে — এই ভয়ে কিছুই করা হয়ে ওঠে না।",
    author: "Kamini Roy",
    role: "Poet & First Female Honours Graduate of British India",
    imageUrl: "",
    gradient: "from-amber-300 to-yellow-600",
    emoji: "✍️",
  },
  {
    text: "কেন পান্থ ক্ষান্ত হও, হেরি দীর্ঘ পথ? উৎসাহে কাজ করো, যা করিবে কর আজই।",
    author: "Kamini Roy",
    role: "Poet & First Female Honours Graduate of British India",
    imageUrl: "",
    gradient: "from-cyan-400 to-teal-600",
    emoji: "🛤️",
  },
  {
    text: "নানান ভূষণে নারী, নানান রূপে সজে, কিন্তু শিক্ষাই তার শ্রেষ্ঠ ভূষণ।",
    author: "Kamini Roy",
    role: "Poet & First Female Honours Graduate of British India",
    imageUrl: "",
    gradient: "from-emerald-400 to-teal-600",
    emoji: "🎓",
  },
  {
    text: "জীবন চলার পথে পদে পদে বাধা আসে, তবু থামিও না, এগিয়ে চলো।",
    author: "Kamini Roy",
    role: "Poet & First Female Honours Graduate of British India",
    imageUrl: "",
    gradient: "from-blue-400 to-indigo-600",
    emoji: "🚶‍♀️",
  },

  // ===== সুফিয়া কামাল (Sufia Kamal) =====
  {
    text: "নারীর পদচারণায় মুখরিত হোক পৃথিবীর প্রতিটি পথ।",
    author: "Sufia Kamal",
    role: "Poet & Women's Rights Activist",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "🪷",
  },
  {
    text: "এই দেশের মাটির গন্ধ আমার রক্তে মিশে আছে।",
    author: "Sufia Kamal",
    role: "Poet & Women's Rights Activist",
    imageUrl: "",
    gradient: "from-red-400 to-pink-600",
    emoji: "🌿",
  },
  {
    text: "আমি নারী, আমি মানুষ — এটাই আমার পরিচয়।",
    author: "Sufia Kamal",
    role: "Poet & Women's Rights Activist",
    imageUrl: "",
    gradient: "from-orange-400 to-red-500",
    emoji: "✊",
  },
  {
    text: "অন্যায়ের প্রতিবাদ করতে না পারলে মানুষ হওয়ার কোনো সার্থকতা নেই।",
    author: "Sufia Kamal",
    role: "Poet & Women's Rights Activist",
    imageUrl: "",
    gradient: "from-violet-400 to-purple-600",
    emoji: "🔥",
  },
  {
    text: "মাতৃভাষার মর্যাদা রক্ষা করা প্রতিটি নাগরিকের কর্তব্য।",
    author: "Sufia Kamal",
    role: "Poet & Women's Rights Activist",
    imageUrl: "",
    gradient: "from-sky-400 to-blue-600",
    emoji: "🗣️",
  },
  {
    text: "কবিতা হলো মানুষের হৃদয়ের ভাষা — সেখানে কোনো ভেদাভেদ নেই।",
    author: "Sufia Kamal",
    role: "Poet & Women's Rights Activist",
    imageUrl: "",
    gradient: "from-pink-400 to-rose-600",
    emoji: "💐",
  },
  {
    text: "জেগে ওঠো, জেগে ওঠো — ঘুমিয়ে থাকলে পিছিয়ে পড়বে।",
    author: "Sufia Kamal",
    role: "Poet & Women's Rights Activist",
    imageUrl: "",
    gradient: "from-amber-400 to-orange-500",
    emoji: "🌅",
  },

  // ===== নবনীতা দেবসেন (Nabaneeta Dev Sen) =====
  {
    text: "হাসি হলো জীবনের সবচেয়ে শক্তিশালী অস্ত্র।",
    author: "Nabaneeta Dev Sen",
    role: "Writer, Poet & Academic",
    imageUrl: "",
    gradient: "from-lime-400 to-green-600",
    emoji: "😄",
  },
  {
    text: "একটা মেয়ের সবচেয়ে বড় পরিচয় হলো সে নিজে — অন্য কারো সম্পর্কে নয়।",
    author: "Nabaneeta Dev Sen",
    role: "Writer, Poet & Academic",
    imageUrl: "",
    gradient: "from-purple-400 to-fuchsia-600",
    emoji: "🌺",
  },
  {
    text: "বাংলা ভাষার যে সৌন্দর্য, তা পৃথিবীর কোনো ভাষায় নেই।",
    author: "Nabaneeta Dev Sen",
    role: "Writer, Poet & Academic",
    imageUrl: "",
    gradient: "from-teal-400 to-emerald-600",
    emoji: "📖",
  },
  {
    text: "জীবনকে গুরুগম্ভীর করে নেওয়ার কোনো মানে নেই — হালকাভাবে নাও, গভীরভাবে ভাবো।",
    author: "Nabaneeta Dev Sen",
    role: "Writer, Poet & Academic",
    imageUrl: "",
    gradient: "from-yellow-400 to-amber-600",
    emoji: "🎭",
  },
  {
    text: "ভ্রমণ মানুষকে বিনয়ী করে — দেখতে শেখায় যে পৃথিবী কত বিশাল।",
    author: "Nabaneeta Dev Sen",
    role: "Writer, Poet & Academic",
    imageUrl: "",
    gradient: "from-blue-400 to-indigo-600",
    emoji: "✈️",
  },
  {
    text: "নারীর শত্রু নারী — এই কথাটা মিথ্যা প্রমাণ করতে হবে আমাদেরই।",
    author: "Nabaneeta Dev Sen",
    role: "Writer, Poet & Academic",
    imageUrl: "",
    gradient: "from-rose-400 to-red-600",
    emoji: "🤝",
  },

  // ===== সুচিত্রা ভট্টাচার্য (Suchitra Bhattacharya) =====
  {
    text: "মিতিন মাসির প্রতিটি রহস্যের পেছনে আছে মানুষের চিরন্তন লোভ আর দুর্বলতা।",
    author: "Suchitra Bhattacharya",
    role: "Novelist & Creator of Mitin Masi",
    imageUrl: "",
    gradient: "from-indigo-400 to-violet-700",
    emoji: "🔍",
  },
  {
    text: "গল্প লেখার সময় আমি নিজেকে চরিত্রের মধ্যে হারিয়ে ফেলি।",
    author: "Suchitra Bhattacharya",
    role: "Novelist & Creator of Mitin Masi",
    imageUrl: "",
    gradient: "from-cyan-400 to-teal-600",
    emoji: "✍️",
  },
  {
    text: "প্রতিটি মানুষের ভেতরে একটা গল্প লুকানো আছে — খুঁজে বের করতে হয়।",
    author: "Suchitra Bhattacharya",
    role: "Novelist & Creator of Mitin Masi",
    imageUrl: "",
    gradient: "from-amber-300 to-yellow-600",
    emoji: "📚",
  },
  {
    text: "একজন লেখকের কাজ হলো সত্যকে সুন্দরভাবে বলা।",
    author: "Suchitra Bhattacharya",
    role: "Novelist & Creator of Mitin Masi",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "🖊️",
  },
  {
    text: "সমাজে মেয়েদের জায়গাটা তারা নিজেরাই তৈরি করে নেয়।",
    author: "Suchitra Bhattacharya",
    role: "Novelist & Creator of Mitin Masi",
    imageUrl: "",
    gradient: "from-pink-400 to-rose-600",
    emoji: "💪",
  },

  // ===== বাণী বসু (Bani Basu) =====
  {
    text: "ইতিহাসের পাতায় যাদের নাম নেই, তাদের কথা বলাই সাহিত্যের কাজ।",
    author: "Bani Basu",
    role: "Novelist & Sahitya Akademi Award Winner",
    imageUrl: "",
    gradient: "from-red-400 to-pink-600",
    emoji: "📜",
  },
  {
    text: "জীবন তো ছোটো — সেই ছোটো জীবনে কত বড়ো স্বপ্ন দেখতে হয়।",
    author: "Bani Basu",
    role: "Novelist & Sahitya Akademi Award Winner",
    imageUrl: "",
    gradient: "from-violet-400 to-purple-600",
    emoji: "🌟",
  },
  {
    text: "পুরুষতান্ত্রিক সমাজে নারীর লড়াইটা দ্বিগুণ কঠিন।",
    author: "Bani Basu",
    role: "Novelist & Sahitya Akademi Award Winner",
    imageUrl: "",
    gradient: "from-emerald-400 to-teal-600",
    emoji: "✊",
  },
  {
    text: "অতীতকে জানা দরকার, কিন্তু অতীতে আটকে থাকা দরকার নয়।",
    author: "Bani Basu",
    role: "Novelist & Sahitya Akademi Award Winner",
    imageUrl: "",
    gradient: "from-sky-400 to-blue-600",
    emoji: "⏳",
  },
  {
    text: "শিল্পীর চোখ দিয়ে দেখলে পৃথিবী অন্যরকম লাগে।",
    author: "Bani Basu",
    role: "Novelist & Sahitya Akademi Award Winner",
    imageUrl: "",
    gradient: "from-orange-400 to-red-500",
    emoji: "🎨",
  },

  // ===== স্বর্ণকুমারী দেবী (Swarnakumari Devi) =====
  {
    text: "নারীশিক্ষাই জাতির উন্নতির প্রথম সোপান।",
    author: "Swarnakumari Devi",
    role: "Writer & First Bengali Woman Novelist",
    imageUrl: "",
    gradient: "from-amber-400 to-orange-500",
    emoji: "📖",
  },
  {
    text: "সাহিত্যের পথে চলতে গেলে নিজের স্বাধীন চিন্তাভাবনা দরকার।",
    author: "Swarnakumari Devi",
    role: "Writer & First Bengali Woman Novelist",
    imageUrl: "",
    gradient: "from-fuchsia-500 to-purple-700",
    emoji: "✍️",
  },
  {
    text: "জ্ঞানই মুক্তি — এটি নারী-পুরুষ সকলের জন্য সমান সত্য।",
    author: "Swarnakumari Devi",
    role: "Writer & First Bengali Woman Novelist",
    imageUrl: "",
    gradient: "from-teal-400 to-emerald-600",
    emoji: "🕊️",
  },
  {
    text: "দেশের সেবা করার অধিকার নারীরও আছে।",
    author: "Swarnakumari Devi",
    role: "Writer & First Bengali Woman Novelist",
    imageUrl: "",
    gradient: "from-blue-400 to-indigo-600",
    emoji: "🇮🇳",
  },

  // ===== সরলা দেবী চৌধুরাণী (Sarala Devi Chaudhurani) =====
  {
    text: "দেশকে ভালোবাসতে হলে দেশের মানুষকে ভালোবাসতে হয়।",
    author: "Sarala Devi Chaudhurani",
    role: "Political Activist & Musician",
    imageUrl: "",
    gradient: "from-rose-400 to-red-600",
    emoji: "❤️",
  },
  {
    text: "শক্তির উপাসনা করো — শক্তি ছাড়া মুক্তি নেই।",
    author: "Sarala Devi Chaudhurani",
    role: "Political Activist & Musician",
    imageUrl: "",
    gradient: "from-lime-400 to-green-600",
    emoji: "💪",
  },
  {
    text: "সংগীত হলো আত্মার ভাষা — তার কোনো সীমানা নেই।",
    author: "Sarala Devi Chaudhurani",
    role: "Political Activist & Musician",
    imageUrl: "",
    gradient: "from-purple-400 to-fuchsia-600",
    emoji: "🎵",
  },
  {
    text: "স্বদেশী আন্দোলন শুধু পুরুষের নয়, নারীরও।",
    author: "Sarala Devi Chaudhurani",
    role: "Political Activist & Musician",
    imageUrl: "",
    gradient: "from-yellow-400 to-amber-600",
    emoji: "🪷",
  },

  // ===== কাদম্বিনী গাঙ্গুলী (Kadambini Ganguly) =====
  {
    text: "চিকিৎসাশাস্ত্রে নারীর প্রবেশ একটি বিপ্লব — এই বিপ্লবে আমি গর্বিত।",
    author: "Kadambini Ganguly",
    role: "One of India's First Female Physicians",
    imageUrl: "",
    gradient: "from-cyan-400 to-teal-600",
    emoji: "⚕️",
  },
  {
    text: "শিক্ষা কোনো বিলাসিতা নয়, এটি প্রতিটি মানুষের অধিকার।",
    author: "Kadambini Ganguly",
    role: "One of India's First Female Physicians",
    imageUrl: "",
    gradient: "from-indigo-400 to-violet-700",
    emoji: "🎓",
  },
  {
    text: "পথ কঠিন হবে, কিন্তু পথ ছাড়বো না — এটাই আমার সংকল্প।",
    author: "Kadambini Ganguly",
    role: "One of India's First Female Physicians",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "🛤️",
  },
  {
    text: "রোগীর সেবা করা ঈশ্বরের সেবার সমান।",
    author: "Kadambini Ganguly",
    role: "One of India's First Female Physicians",
    imageUrl: "",
    gradient: "from-amber-300 to-yellow-600",
    emoji: "🏥",
  },

  // ===== সুচিত্রা সেন (Suchitra Sen) =====
  {
    text: "অভিনয় আমার ধ্যান — ক্যামেরার সামনে দাঁড়ালে পৃথিবী ভুলে যাই।",
    author: "Suchitra Sen",
    role: "Legendary Film Actress",
    imageUrl: "",
    gradient: "from-pink-400 to-rose-600",
    emoji: "🎬",
  },
  {
    text: "নিজের একান্ত জগতটাকে রক্ষা করাও একটা শিল্প।",
    author: "Suchitra Sen",
    role: "Legendary Film Actress",
    imageUrl: "",
    gradient: "from-slate-400 to-gray-700",
    emoji: "🎭",
  },
  {
    text: "শিল্পীর জীবন নিভৃতেই সুন্দর।",
    author: "Suchitra Sen",
    role: "Legendary Film Actress",
    imageUrl: "",
    gradient: "from-violet-400 to-purple-600",
    emoji: "🌸",
  },
  {
    text: "চরিত্রকে বাঁচিয়ে তুলতে হলে নিজেকে ভুলতে হয়।",
    author: "Suchitra Sen",
    role: "Legendary Film Actress",
    imageUrl: "",
    gradient: "from-red-400 to-pink-600",
    emoji: "🎥",
  },

  // ===== অপর্ণা সেন (Aparna Sen) =====
  {
    text: "সিনেমা হলো সমাজের আয়না — সেই আয়নায় সত্য প্রতিফলিত হওয়া উচিত।",
    author: "Aparna Sen",
    role: "Filmmaker, Actress & Intellectual",
    imageUrl: "",
    gradient: "from-blue-400 to-indigo-600",
    emoji: "🎬",
  },
  {
    text: "একটি ভালো চলচ্চিত্র মানুষকে ভাবায়, নড়ায়, বদলায়।",
    author: "Aparna Sen",
    role: "Filmmaker, Actress & Intellectual",
    imageUrl: "",
    gradient: "from-emerald-400 to-teal-600",
    emoji: "🎥",
  },
  {
    text: "মেয়েরা যখন নিজের গল্প নিজে বলে, তখন সেটা একটা বিপ্লব।",
    author: "Aparna Sen",
    role: "Filmmaker, Actress & Intellectual",
    imageUrl: "",
    gradient: "from-rose-400 to-red-600",
    emoji: "📣",
  },
  {
    text: "শিল্পের কোনো সীমানা নেই, কোনো ধর্ম নেই, কোনো জাত নেই।",
    author: "Aparna Sen",
    role: "Filmmaker, Actress & Intellectual",
    imageUrl: "",
    gradient: "from-orange-400 to-red-500",
    emoji: "🎨",
  },
  {
    text: "প্রশ্ন করার সাহস থাকা উচিত — প্রশ্ন না করলে উত্তর পাওয়া যায় না।",
    author: "Aparna Sen",
    role: "Filmmaker, Actress & Intellectual",
    imageUrl: "",
    gradient: "from-teal-400 to-emerald-600",
    emoji: "❓",
  },
  {
    text: "বাঙালি সংস্কৃতির সমৃদ্ধি এতটাই গভীর যে তা পৃথিবীকে আলোকিত করতে পারে।",
    author: "Aparna Sen",
    role: "Filmmaker, Actress & Intellectual",
    imageUrl: "",
    gradient: "from-amber-400 to-orange-500",
    emoji: "🪔",
  },

  // ===== ঝুলন গোস্বামী (Jhulan Goswami) =====
  {
    text: "ক্রিকেট আমার জীবন, আমার আবেগ, আমার সবকিছু।",
    author: "Jhulan Goswami",
    role: "Legendary Cricketer & Fast Bowler",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "🏏",
  },
  {
    text: "ছোটো শহর থেকে এসেছি বলে স্বপ্নটা ছোটো হবে কেন?",
    author: "Jhulan Goswami",
    role: "Legendary Cricketer & Fast Bowler",
    imageUrl: "",
    gradient: "from-sky-400 to-blue-600",
    emoji: "⭐",
  },
  {
    text: "পরিশ্রমের কোনো বিকল্প নেই — প্রতিভা থাকলেও পরিশ্রম করতে হয়।",
    author: "Jhulan Goswami",
    role: "Legendary Cricketer & Fast Bowler",
    imageUrl: "",
    gradient: "from-lime-400 to-green-600",
    emoji: "💪",
  },
  {
    text: "মেয়েদের ক্রিকেটকে সম্মান দিন — আমরা দেশের জন্য খেলি।",
    author: "Jhulan Goswami",
    role: "Legendary Cricketer & Fast Bowler",
    imageUrl: "",
    gradient: "from-blue-400 to-indigo-600",
    emoji: "🇮🇳",
  },
  {
    text: "হার মানা আমার অভিধানে নেই।",
    author: "Jhulan Goswami",
    role: "Legendary Cricketer & Fast Bowler",
    imageUrl: "",
    gradient: "from-red-400 to-pink-600",
    emoji: "🏏",
  },
  {
    text: "চকোলগঞ্জের মাঠ থেকে লর্ডস — এটাই আমার যাত্রা।",
    author: "Jhulan Goswami",
    role: "Legendary Cricketer & Fast Bowler",
    imageUrl: "",
    gradient: "from-amber-300 to-yellow-600",
    emoji: "🛤️",
  },

  // ===== ডোলা ব্যানার্জী (Dola Banerjee) =====
  {
    text: "তীরন্দাজি আমাকে শিখিয়েছে ধৈর্য ধরতে এবং লক্ষ্যে স্থির থাকতে।",
    author: "Dola Banerjee",
    role: "Archer & Arjuna Award Winner",
    imageUrl: "",
    gradient: "from-cyan-400 to-teal-600",
    emoji: "🏹",
  },
  {
    text: "একটি তীর ছোড়ার আগে মনটাকে শান্ত করতে হয়।",
    author: "Dola Banerjee",
    role: "Archer & Arjuna Award Winner",
    imageUrl: "",
    gradient: "from-purple-400 to-fuchsia-600",
    emoji: "🎯",
  },

  // ===== মল্লিকা সেনগুপ্ত (Mallika Sengupta) =====
  {
    text: "কবিতা হলো নারীর মুক্তির ভাষা।",
    author: "Mallika Sengupta",
    role: "Feminist Poet & Writer",
    imageUrl: "",
    gradient: "from-fuchsia-500 to-purple-700",
    emoji: "✍️",
  },
  {
    text: "যে সমাজ নারীকে কবি হতে দেয় না, সে সমাজ মৃত।",
    author: "Mallika Sengupta",
    role: "Feminist Poet & Writer",
    imageUrl: "",
    gradient: "from-rose-400 to-red-600",
    emoji: "🔥",
  },
  {
    text: "আমার কবিতা আমার প্রতিবাদ — আমার শব্দ আমার অস্ত্র।",
    author: "Mallika Sengupta",
    role: "Feminist Poet & Writer",
    imageUrl: "",
    gradient: "from-indigo-400 to-violet-700",
    emoji: "🖊️",
  },
  {
    text: "নারীর শরীর নারীর নিজের — এই সত্যটা সবাইকে বুঝতে হবে।",
    author: "Mallika Sengupta",
    role: "Feminist Poet & Writer",
    imageUrl: "",
    gradient: "from-pink-400 to-rose-600",
    emoji: "✊",
  },

  // ===== সরোজিনী নাইডু (Sarojini Naidu) =====
  {
    text: "আমরা নতুন ভারতের নারী — আমরা ভয় পাই না।",
    author: "Sarojini Naidu",
    role: "Poet, Freedom Fighter & Nightingale of India",
    imageUrl: "",
    gradient: "from-amber-400 to-orange-500",
    emoji: "🪷",
  },
  {
    text: "জীবনের প্রতিটি মুহূর্ত একটি কবিতা — যদি তুমি তা অনুভব করতে পারো।",
    author: "Sarojini Naidu",
    role: "Poet, Freedom Fighter & Nightingale of India",
    imageUrl: "",
    gradient: "from-violet-400 to-purple-600",
    emoji: "🌺",
  },
  {
    text: "স্বাধীনতা কেউ দান করে না, অর্জন করতে হয়।",
    author: "Sarojini Naidu",
    role: "Poet, Freedom Fighter & Nightingale of India",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "🕊️",
  },
  {
    text: "দেশপ্রেম হলো সেই শক্তি যা পাহাড়কেও সরাতে পারে।",
    author: "Sarojini Naidu",
    role: "Poet, Freedom Fighter & Nightingale of India",
    imageUrl: "",
    gradient: "from-orange-400 to-red-500",
    emoji: "🏔️",
  },
  {
    text: "গান গাও, কবিতা লেখো — সৌন্দর্যের সেবা করো।",
    author: "Sarojini Naidu",
    role: "Poet, Freedom Fighter & Nightingale of India",
    imageUrl: "",
    gradient: "from-teal-400 to-emerald-600",
    emoji: "🎶",
  },

  // ===== মমতা বন্দ্যোপাধ্যায় (Mamata Banerjee) =====
  {
    text: "মা, মাটি, মানুষ — এই তিনই আমার রাজনীতির ভিত্তি।",
    author: "Mamata Banerjee",
    role: "Chief Minister of West Bengal",
    imageUrl: "",
    gradient: "from-blue-400 to-indigo-600",
    emoji: "🌾",
  },
  {
    text: "লড়াই করতে জানি, হার মানতে জানি না।",
    author: "Mamata Banerjee",
    role: "Chief Minister of West Bengal",
    imageUrl: "",
    gradient: "from-sky-400 to-blue-600",
    emoji: "✊",
  },
  {
    text: "গরিবের পাশে দাঁড়ানোই সবচেয়ে বড় রাজনীতি।",
    author: "Mamata Banerjee",
    role: "Chief Minister of West Bengal",
    imageUrl: "",
    gradient: "from-emerald-400 to-teal-600",
    emoji: "🤝",
  },
  {
    text: "বাংলার সংস্কৃতি, বাংলার ঐতিহ্য — এটাই আমাদের পরিচয়।",
    author: "Mamata Banerjee",
    role: "Chief Minister of West Bengal",
    imageUrl: "",
    gradient: "from-yellow-400 to-amber-600",
    emoji: "🪷",
  },
  {
    text: "একজন সাধারণ মানুষ চাইলে অসাধারণ কাজ করতে পারে।",
    author: "Mamata Banerjee",
    role: "Chief Minister of West Bengal",
    imageUrl: "",
    gradient: "from-red-400 to-pink-600",
    emoji: "⭐",
  },

  // ===== জয়া বচ্চন (Jaya Bachchan) =====
  {
    text: "বাঙালি হওয়াটা আমার গর্ব — এই সংস্কৃতি আমাকে তৈরি করেছে।",
    author: "Jaya Bachchan",
    role: "Actress & Politician (Bengali Origin)",
    imageUrl: "",
    gradient: "from-pink-400 to-rose-600",
    emoji: "🎬",
  },
  {
    text: "অভিনয়ে সততা থাকতে হয়, নাহলে দর্শক বুঝে যায়।",
    author: "Jaya Bachchan",
    role: "Actress & Politician (Bengali Origin)",
    imageUrl: "",
    gradient: "from-amber-300 to-yellow-600",
    emoji: "🎭",
  },
  {
    text: "নারীকে দুর্বল ভাবা সমাজের সবচেয়ে বড় ভুল।",
    author: "Jaya Bachchan",
    role: "Actress & Politician (Bengali Origin)",
    imageUrl: "",
    gradient: "from-violet-400 to-purple-600",
    emoji: "💪",
  },

  // ===== প্রীতিলতা ওয়াদ্দেদার (Pritilata Waddedar) =====
  {
    text: "দেশের জন্য প্রাণ দিতে পারাটা সৌভাগ্যের।",
    author: "Pritilata Waddedar",
    role: "Revolutionary Independence Activist",
    imageUrl: "",
    gradient: "from-red-400 to-pink-600",
    emoji: "🔥",
  },
  {
    text: "ভয়কে জয় করাই বিপ্লবের প্রথম ধাপ।",
    author: "Pritilata Waddedar",
    role: "Revolutionary Independence Activist",
    imageUrl: "",
    gradient: "from-slate-400 to-gray-700",
    emoji: "⚔️",
  },
  {
    text: "মেয়ে হয়ে জন্মেছি বলে কি স্বাধীনতার যুদ্ধে অংশ নিতে পারবো না?",
    author: "Pritilata Waddedar",
    role: "Revolutionary Independence Activist",
    imageUrl: "",
    gradient: "from-orange-400 to-red-500",
    emoji: "✊",
  },

  // ===== মাতঙ্গিনী হাজরা (Matangini Hazra) =====
  {
    text: "বন্দে মাতরম — এই মন্ত্র বুকে নিয়ে এগিয়ে চলো।",
    author: "Matangini Hazra",
    role: "Freedom Fighter & Revolutionary",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "🇮🇳",
  },
  {
    text: "পতাকা হাতে থাকবে, পিছু হটবো না।",
    author: "Matangini Hazra",
    role: "Freedom Fighter & Revolutionary",
    imageUrl: "",
    gradient: "from-amber-400 to-orange-500",
    emoji: "🚩",
  },

  // ===== লীলা মজুমদার (Leela Majumdar) =====
  {
    text: "শিশুদের জন্য লেখা সবচেয়ে কঠিন — তাদের সাথে মিথ্যা বলা যায় না।",
    author: "Leela Majumdar",
    role: "Children's Author & Writer",
    imageUrl: "",
    gradient: "from-cyan-400 to-teal-600",
    emoji: "📚",
  },
  {
    text: "রান্না আর লেখা — দুটোতেই একটা জাদু আছে।",
    author: "Leela Majumdar",
    role: "Children's Author & Writer",
    imageUrl: "",
    gradient: "from-lime-400 to-green-600",
    emoji: "🍳",
  },
  {
    text: "হাসির গল্পের পেছনে কখনো কখনো গভীর দুঃখ থাকে।",
    author: "Leela Majumdar",
    role: "Children's Author & Writer",
    imageUrl: "",
    gradient: "from-purple-400 to-fuchsia-600",
    emoji: "😊",
  },

  // ===== সাবিত্রীবাই ফুলে (Savitribai Phule) =====
  {
    text: "শিক্ষা হলো সেই অস্ত্র যা দিয়ে সব বাধা ভাঙা যায়।",
    author: "Savitribai Phule",
    role: "India's First Female Teacher & Social Reformer",
    imageUrl: "",
    gradient: "from-indigo-400 to-violet-700",
    emoji: "🎓",
  },
  {
    text: "জাত-পাতের বেড়া ভেঙে দাও — সবাই সমান, সবার অধিকার সমান।",
    author: "Savitribai Phule",
    role: "India's First Female Teacher & Social Reformer",
    imageUrl: "",
    gradient: "from-teal-400 to-emerald-600",
    emoji: "⚖️",
  },
  {
    text: "বিদ্যা অর্জন করো, আত্মনির্ভর হও, স্বাধীন হও।",
    author: "Savitribai Phule",
    role: "India's First Female Teacher & Social Reformer",
    imageUrl: "",
    gradient: "from-rose-400 to-red-600",
    emoji: "📖",
  },

  // ===== নার্গিস দত্ত (Nargis Dutt) =====
  {
    text: "অভিনয় আমার কাছে শুধু পেশা নয়, এটা আমার জীবন।",
    author: "Nargis Dutt",
    role: "Iconic Film Actress",
    imageUrl: "",
    gradient: "from-pink-400 to-rose-600",
    emoji: "🎬",
  },
  {
    text: "একটি ভালো ছবি সমাজকে বদলে দিতে পারে।",
    author: "Nargis Dutt",
    role: "Iconic Film Actress",
    imageUrl: "",
    gradient: "from-fuchsia-500 to-purple-700",
    emoji: "🎥",
  },

  // ===== মৈত্রেয়ী দেবী (Maitreyee Devi) =====
  {
    text: "প্রেম কোনো দুর্বলতা নয়, এটি জীবনের সবচেয়ে বড় শক্তি।",
    author: "Maitreyee Devi",
    role: "Writer & Poet",
    imageUrl: "",
    gradient: "from-red-400 to-pink-600",
    emoji: "❤️",
  },
  {
    text: "একজন নারীর স্মৃতি তার সবচেয়ে বিশ্বস্ত সঙ্গী।",
    author: "Maitreyee Devi",
    role: "Writer & Poet",
    imageUrl: "",
    gradient: "from-violet-400 to-purple-600",
    emoji: "📖",
  },
  {
    text: "দর্শন ও সাহিত্য একসাথে চলে — একটি ছাড়া অন্যটি অপূর্ণ।",
    author: "Maitreyee Devi",
    role: "Writer & Poet",
    imageUrl: "",
    gradient: "from-sky-400 to-blue-600",
    emoji: "✍️",
  },

  // ===== অমৃতা প্রীতম (Amrita Pritam — wrote extensively in Bengali context) =====
  {
    text: "প্রেম না পেলে মানুষ বাঁচে, কিন্তু বেঁচে থাকাটাই কঠিন হয়ে যায়।",
    author: "Amrita Pritam",
    role: "Poet & Novelist, Sahitya Akademi Fellow",
    imageUrl: "",
    gradient: "from-amber-300 to-yellow-600",
    emoji: "💔",
  },

  // ===== ইন্দিরা দেবী চৌধুরাণী (Indira Devi Chaudhurani) =====
  {
    text: "সংগীতের মধ্যে দিয়ে মানুষের আত্মা কথা বলে।",
    author: "Indira Devi Chaudhurani",
    role: "Musician & Educationist (Tagore Family)",
    imageUrl: "",
    gradient: "from-emerald-400 to-teal-600",
    emoji: "🎵",
  },
  {
    text: "রবীন্দ্রসংগীত বাঙালির প্রাণের সংগীত।",
    author: "Indira Devi Chaudhurani",
    role: "Musician & Educationist (Tagore Family)",
    imageUrl: "",
    gradient: "from-orange-400 to-red-500",
    emoji: "🎶",
  },

  // ===== সানু লাহিড়ী (Sanu Lahiri) / আধুনিক কবি =====
  {
    text: "বাংলা কবিতা মানেই বিদ্রোহ, বাংলা কবিতা মানেই প্রেম।",
    author: "Ketaki Kushari Dyson",
    role: "Poet, Writer & Translator",
    imageUrl: "",
    gradient: "from-blue-400 to-indigo-600",
    emoji: "✍️",
  },

  // ===== রাধারানী দেবী (Radharani Devi) =====
  {
    text: "সংসার সামলানোও একটা শিল্প — সেই শিল্পী হলো নারী।",
    author: "Radharani Devi",
    role: "Writer & Social Worker",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "🏠",
  },

  // ===== মীরা দেবী (Mira Devi, Tagore family) =====
  {
    text: "বাবার চোখ দিয়ে পৃথিবী দেখেছি — সেই দেখাটাই আমার সম্পদ।",
    author: "Mira Devi",
    role: "Rabindranath Tagore's Daughter",
    imageUrl: "",
    gradient: "from-rose-400 to-red-600",
    emoji: "🪷",
  },

  // ===== Additional from key figures to reach 110 =====

  // More Begum Rokeya
  {
    text: "নারী জাগরণ ছাড়া সমাজের প্রকৃত জাগরণ সম্ভব নয়।",
    author: "Begum Rokeya Sakhawat Hossain",
    role: "Writer, Educator & Social Activist",
    imageUrl: "",
    gradient: "from-lime-400 to-green-600",
    emoji: "🌅",
  },

  // More Kamini Roy
  {
    text: "আজি হতে চিরদিন সংকল্প করিলাম, নিজে পথ চলিব আমি, নিজেরই আলো জ্বালিব।",
    author: "Kamini Roy",
    role: "Poet & First Female Honours Graduate of British India",
    imageUrl: "",
    gradient: "from-yellow-400 to-amber-600",
    emoji: "🪔",
  },

  // More Ashapurna Devi
  {
    text: "সমাজ বদলাতে গেলে প্রথমে নিজেকে বদলাতে হয়।",
    author: "Ashapurna Devi",
    role: "Novelist & Jnanpith Award Winner",
    imageUrl: "",
    gradient: "from-cyan-400 to-teal-600",
    emoji: "🔄",
  },

  // More Mahasweta Devi
  {
    text: "যে লেখক মানুষের পাশে দাঁড়ায় না, তার লেখার কোনো মূল্য নেই।",
    author: "Mahasweta Devi",
    role: "Writer, Activist & Magsaysay Award Winner",
    imageUrl: "",
    gradient: "from-purple-400 to-fuchsia-600",
    emoji: "📖",
  },

  // More Sufia Kamal
  {
    text: "ফুল ফোটানোর জন্য কাঁটার ব্যথা সহ্য করতে হয়।",
    author: "Sufia Kamal",
    role: "Poet & Women's Rights Activist",
    imageUrl: "",
    gradient: "from-pink-400 to-rose-600",
    emoji: "🌹",
  },

  // Lila Ray (literary translator)
  {
    text: "অনুবাদ হলো দুই সংস্কৃতির মধ্যে সেতুবন্ধন।",
    author: "Lila Ray",
    role: "Writer & Literary Translator",
    imageUrl: "",
    gradient: "from-indigo-400 to-violet-700",
    emoji: "🌉",
  },

  // More Nabaneeta Dev Sen
  {
    text: "রসবোধ না থাকলে জীবন অসহ্য হয়ে যায়।",
    author: "Nabaneeta Dev Sen",
    role: "Writer, Poet & Academic",
    imageUrl: "",
    gradient: "from-amber-400 to-orange-500",
    emoji: "😄",
  },

  // More Suchitra Bhattacharya
  {
    text: "রহস্য সমাধানের চেয়ে মানুষের মনের রহস্য বেশি জটিল।",
    author: "Suchitra Bhattacharya",
    role: "Novelist & Creator of Mitin Masi",
    imageUrl: "",
    gradient: "from-slate-400 to-gray-700",
    emoji: "🔍",
  },

  // Rani Rashmoni
  {
    text: "ধর্ম ও সেবা একসাথে চলে — মানুষের সেবাই সবচেয়ে বড় ধর্ম।",
    author: "Rani Rashmoni",
    role: "Philanthropist & Builder of Dakshineswar Temple",
    imageUrl: "",
    gradient: "from-fuchsia-500 to-purple-700",
    emoji: "🛕",
  },

  // More Aparna Sen
  {
    text: "চলচ্চিত্র একটি ভাষা — সেই ভাষায় আমি আমার কথা বলি।",
    author: "Aparna Sen",
    role: "Filmmaker, Actress & Intellectual",
    imageUrl: "",
    gradient: "from-teal-400 to-emerald-600",
    emoji: "🎬",
  },

  // More Mamata Banerjee
  {
    text: "জনগণই আমার শক্তি, জনগণই আমার অনুপ্রেরণা।",
    author: "Mamata Banerjee",
    role: "Chief Minister of West Bengal",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "🌾",
  },

  // More Jhulan Goswami
  {
    text: "প্রতিটি ম্যাচ একটি নতুন সুযোগ — আগের হার ভুলে যাও, সামনে এগিয়ে চলো।",
    author: "Jhulan Goswami",
    role: "Legendary Cricketer & Fast Bowler",
    imageUrl: "",
    gradient: "from-emerald-400 to-teal-600",
    emoji: "🏏",
  },
];
