import { Quote } from '../types';

export const historicalQuotes: Quote[] = [
  // === ANCIENT WORLD ===
  {
    text: "I will not be triumphed over.",
    author: "Cleopatra VII",
    role: "Queen of Egypt",
    imageUrl: "",
    gradient: "from-amber-400 to-amber-600",
    emoji: "👑",
  },
  {
    text: "In the past, no one has ever made war on us. We have been content with what we had.",
    author: "Cleopatra VII",
    role: "Queen of Egypt",
    imageUrl: "",
    gradient: "from-yellow-400 to-amber-600",
    emoji: "🏛️",
  },
  {
    text: "All formal dogmatic religions are fallacious and must never be accepted by self-respecting persons as final.",
    author: "Hypatia of Alexandria",
    role: "Philosopher & Mathematician",
    imageUrl: "",
    gradient: "from-indigo-400 to-indigo-600",
    emoji: "📐",
  },
  {
    text: "Reserve your right to think, for even to think wrongly is better than not to think at all.",
    author: "Hypatia of Alexandria",
    role: "Philosopher & Mathematician",
    imageUrl: "",
    gradient: "from-violet-400 to-indigo-600",
    emoji: "🔭",
  },
  {
    text: "To teach superstitions as truth is a most terrible thing.",
    author: "Hypatia of Alexandria",
    role: "Philosopher & Mathematician",
    imageUrl: "",
    gradient: "from-purple-400 to-indigo-600",
    emoji: "📜",
  },
  {
    text: "Some say an army of horsemen, some of infantry, some of ships, is the fairest thing on the dark earth; but I say it is whatsoever one loves.",
    author: "Sappho",
    role: "Ancient Greek Poet",
    imageUrl: "",
    gradient: "from-rose-400 to-pink-600",
    emoji: "🎵",
  },
  {
    text: "What is beautiful is good, and who is good will soon be beautiful.",
    author: "Sappho",
    role: "Ancient Greek Poet",
    imageUrl: "",
    gradient: "from-pink-400 to-rose-600",
    emoji: "🌸",
  },
  {
    text: "He is more than a hero, he is a god in my eyes.",
    author: "Sappho",
    role: "Ancient Greek Poet",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-pink-600",
    emoji: "🏺",
  },

  // === MEDIEVAL & RENAISSANCE ===
  {
    text: "I am not afraid. I was born to do this.",
    author: "Joan of Arc",
    role: "French Heroine & Saint",
    imageUrl: "",
    gradient: "from-blue-400 to-blue-600",
    emoji: "⚔️",
  },
  {
    text: "Act, and God will act.",
    author: "Joan of Arc",
    role: "French Heroine & Saint",
    imageUrl: "",
    gradient: "from-sky-400 to-blue-600",
    emoji: "🛡️",
  },
  {
    text: "One life is all we have and we live it as we believe in living it. But to sacrifice what you are and to live without belief, that is a fate more terrible than dying.",
    author: "Joan of Arc",
    role: "French Heroine & Saint",
    imageUrl: "",
    gradient: "from-slate-400 to-blue-600",
    emoji: "🔥",
  },
  {
    text: "The Word is living, being, spirit, all verdant greening, all creativity.",
    author: "Hildegard of Bingen",
    role: "Abbess, Composer & Mystic",
    imageUrl: "",
    gradient: "from-emerald-400 to-green-600",
    emoji: "🌿",
  },
  {
    text: "Dare to declare who you are. It is not far from the shores of silence to the boundaries of speech.",
    author: "Hildegard of Bingen",
    role: "Abbess, Composer & Mystic",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "🎶",
  },
  {
    text: "Humanity, take a good look at yourself. Inside, you have heaven and earth, and all of creation.",
    author: "Hildegard of Bingen",
    role: "Abbess, Composer & Mystic",
    imageUrl: "",
    gradient: "from-teal-400 to-green-600",
    emoji: "🕊️",
  },
  {
    text: "If you live in the world of sensibility and emotions, the world around you naturally colors your writing.",
    author: "Murasaki Shikibu",
    role: "Japanese Novelist & Poet",
    imageUrl: "",
    gradient: "from-red-400 to-rose-600",
    emoji: "🎋",
  },
  {
    text: "Real things in the darkness seem no realer than dreams.",
    author: "Murasaki Shikibu",
    role: "Japanese Novelist & Poet",
    imageUrl: "",
    gradient: "from-stone-400 to-red-600",
    emoji: "🌙",
  },

  // === QUEEN ELIZABETH I ===
  {
    text: "I know I have the body of a weak and feeble woman, but I have the heart and stomach of a king.",
    author: "Queen Elizabeth I",
    role: "Queen of England",
    imageUrl: "",
    gradient: "from-red-400 to-red-600",
    emoji: "👑",
  },
  {
    text: "I do not want a husband who honours me as a queen, if he does not love me as a woman.",
    author: "Queen Elizabeth I",
    role: "Queen of England",
    imageUrl: "",
    gradient: "from-rose-400 to-red-600",
    emoji: "🏰",
  },
  {
    text: "A clear and innocent conscience fears nothing.",
    author: "Queen Elizabeth I",
    role: "Queen of England",
    imageUrl: "",
    gradient: "from-amber-400 to-red-600",
    emoji: "🦁",
  },
  {
    text: "I would rather be a beggar and single than a queen and married.",
    author: "Queen Elizabeth I",
    role: "Queen of England",
    imageUrl: "",
    gradient: "from-orange-400 to-red-600",
    emoji: "💎",
  },

  // === CATHERINE THE GREAT ===
  {
    text: "I shall be an autocrat: that's my trade. And the good Lord will forgive me: that's His.",
    author: "Catherine the Great",
    role: "Empress of Russia",
    imageUrl: "",
    gradient: "from-cyan-400 to-blue-600",
    emoji: "🏛️",
  },
  {
    text: "A great wind is blowing, and that gives you either imagination or a headache.",
    author: "Catherine the Great",
    role: "Empress of Russia",
    imageUrl: "",
    gradient: "from-blue-400 to-cyan-600",
    emoji: "🌬️",
  },
  {
    text: "In my position you have to read when you want to write and to talk when you would like to read.",
    author: "Catherine the Great",
    role: "Empress of Russia",
    imageUrl: "",
    gradient: "from-slate-400 to-cyan-600",
    emoji: "📖",
  },

  // === INDIAN HEROINES ===
  {
    text: "We fight for independence. If we win, we live; if we die, we attain salvation.",
    author: "Rani Lakshmibai",
    role: "Queen of Jhansi",
    imageUrl: "",
    gradient: "from-orange-400 to-orange-600",
    emoji: "⚔️",
  },
  {
    text: "I will not give up my Jhansi.",
    author: "Rani Lakshmibai",
    role: "Queen of Jhansi",
    imageUrl: "",
    gradient: "from-amber-400 to-orange-600",
    emoji: "🏹",
  },
  {
    text: "A lack of learning is nothing but gross darkness.",
    author: "Savitribai Phule",
    role: "Indian Social Reformer & Educator",
    imageUrl: "",
    gradient: "from-yellow-400 to-orange-600",
    emoji: "📚",
  },
  {
    text: "Go, get education. Be self-reliant, be industrious. Work, gather wisdom and riches.",
    author: "Savitribai Phule",
    role: "Indian Social Reformer & Educator",
    imageUrl: "",
    gradient: "from-orange-400 to-yellow-600",
    emoji: "🌅",
  },

  // === ABOLITIONISTS & SUFFRAGISTS ===
  {
    text: "Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars.",
    author: "Harriet Tubman",
    role: "Abolitionist & Activist",
    imageUrl: "",
    gradient: "from-violet-400 to-purple-600",
    emoji: "⭐",
  },
  {
    text: "I freed a thousand slaves. I could have freed a thousand more if only they knew they were slaves.",
    author: "Harriet Tubman",
    role: "Abolitionist & Activist",
    imageUrl: "",
    gradient: "from-purple-400 to-violet-600",
    emoji: "🔗",
  },
  {
    text: "I had reasoned this out in my mind; there was one of two things I had a right to, liberty or death.",
    author: "Harriet Tubman",
    role: "Abolitionist & Activist",
    imageUrl: "",
    gradient: "from-indigo-400 to-purple-600",
    emoji: "🌟",
  },
  {
    text: "I am not going to die, I'm going home like a shooting star.",
    author: "Sojourner Truth",
    role: "Abolitionist & Women's Rights Activist",
    imageUrl: "",
    gradient: "from-amber-400 to-yellow-600",
    emoji: "🌠",
  },
  {
    text: "Truth is powerful and it prevails.",
    author: "Sojourner Truth",
    role: "Abolitionist & Women's Rights Activist",
    imageUrl: "",
    gradient: "from-yellow-400 to-yellow-600",
    emoji: "✊",
  },
  {
    text: "If women want any rights more than they's got, why don't they just take them, and not be talking about it.",
    author: "Sojourner Truth",
    role: "Abolitionist & Women's Rights Activist",
    imageUrl: "",
    gradient: "from-orange-400 to-amber-600",
    emoji: "💪",
  },
  {
    text: "Failure is impossible.",
    author: "Susan B. Anthony",
    role: "Suffragist & Civil Rights Leader",
    imageUrl: "",
    gradient: "from-blue-400 to-indigo-600",
    emoji: "🗳️",
  },
  {
    text: "Cautious, careful people, always casting about to preserve their reputation and social standing, never can bring about a reform.",
    author: "Susan B. Anthony",
    role: "Suffragist & Civil Rights Leader",
    imageUrl: "",
    gradient: "from-indigo-400 to-blue-600",
    emoji: "📢",
  },
  {
    text: "Independence is happiness.",
    author: "Susan B. Anthony",
    role: "Suffragist & Civil Rights Leader",
    imageUrl: "",
    gradient: "from-sky-400 to-indigo-600",
    emoji: "🗽",
  },

  // === WRITERS & THINKERS (18TH-19TH CENTURY) ===
  {
    text: "I do not wish women to have power over men; but over themselves.",
    author: "Mary Wollstonecraft",
    role: "Writer & Philosopher",
    imageUrl: "",
    gradient: "from-teal-400 to-teal-600",
    emoji: "🪶",
  },
  {
    text: "Strengthen the female mind by enlarging it, and there will be an end to blind obedience.",
    author: "Mary Wollstonecraft",
    role: "Writer & Philosopher",
    imageUrl: "",
    gradient: "from-cyan-400 to-teal-600",
    emoji: "📖",
  },
  {
    text: "I declare after all there is no enjoyment like reading!",
    author: "Jane Austen",
    role: "Novelist",
    imageUrl: "",
    gradient: "from-pink-400 to-pink-600",
    emoji: "📕",
  },
  {
    text: "There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves; it is not my nature.",
    author: "Jane Austen",
    role: "Novelist",
    imageUrl: "",
    gradient: "from-rose-400 to-pink-600",
    emoji: "🌹",
  },
  {
    text: "One half of the world cannot understand the pleasures of the other.",
    author: "Jane Austen",
    role: "Novelist",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-rose-600",
    emoji: "🫖",
  },
  {
    text: "It is never too late to be what you might have been.",
    author: "George Eliot",
    role: "Novelist",
    imageUrl: "",
    gradient: "from-emerald-400 to-emerald-600",
    emoji: "🌱",
  },
  {
    text: "The strongest principle of growth lies in the human choice.",
    author: "George Eliot",
    role: "Novelist",
    imageUrl: "",
    gradient: "from-green-400 to-teal-600",
    emoji: "🌳",
  },
  {
    text: "What do we live for, if it is not to make life less difficult for each other?",
    author: "George Eliot",
    role: "Novelist",
    imageUrl: "",
    gradient: "from-lime-400 to-green-600",
    emoji: "🤝",
  },
  {
    text: "Adventure is worthwhile in itself.",
    author: "Amelia Earhart",
    role: "Aviation Pioneer",
    imageUrl: "",
    gradient: "from-sky-400 to-sky-600",
    emoji: "✈️",
  },
  {
    text: "The most difficult thing is the decision to act, the rest is merely tenacity.",
    author: "Amelia Earhart",
    role: "Aviation Pioneer",
    imageUrl: "",
    gradient: "from-blue-400 to-sky-600",
    emoji: "🌤️",
  },
  {
    text: "The most effective way to do it, is to do it.",
    author: "Amelia Earhart",
    role: "Aviation Pioneer",
    imageUrl: "",
    gradient: "from-cyan-400 to-sky-600",
    emoji: "🧭",
  },
  {
    text: "Never do things others can do and will do, if there are things others cannot do or will not do.",
    author: "Amelia Earhart",
    role: "Aviation Pioneer",
    imageUrl: "",
    gradient: "from-indigo-400 to-sky-600",
    emoji: "🗺️",
  },

  // === FLORENCE NIGHTINGALE ===
  {
    text: "I attribute my success to this: I never gave or took any excuse.",
    author: "Florence Nightingale",
    role: "Founder of Modern Nursing",
    imageUrl: "",
    gradient: "from-red-400 to-pink-600",
    emoji: "🏥",
  },
  {
    text: "I think one's feelings waste themselves in words; they ought all to be distilled into actions which bring results.",
    author: "Florence Nightingale",
    role: "Founder of Modern Nursing",
    imageUrl: "",
    gradient: "from-rose-400 to-rose-600",
    emoji: "🕯️",
  },
  {
    text: "How very little can be done under the spirit of fear.",
    author: "Florence Nightingale",
    role: "Founder of Modern Nursing",
    imageUrl: "",
    gradient: "from-pink-400 to-fuchsia-600",
    emoji: "💉",
  },

  // === MARIE CURIE ===
  {
    text: "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.",
    author: "Marie Curie",
    role: "Physicist & Chemist, Nobel Laureate",
    imageUrl: "",
    gradient: "from-emerald-400 to-teal-600",
    emoji: "🔬",
  },
  {
    text: "Be less curious about people and more curious about ideas.",
    author: "Marie Curie",
    role: "Physicist & Chemist, Nobel Laureate",
    imageUrl: "",
    gradient: "from-teal-400 to-cyan-600",
    emoji: "⚗️",
  },
  {
    text: "I was taught that the way of progress is neither swift nor easy.",
    author: "Marie Curie",
    role: "Physicist & Chemist, Nobel Laureate",
    imageUrl: "",
    gradient: "from-cyan-400 to-emerald-600",
    emoji: "🧪",
  },
  {
    text: "One never notices what has been done; one can only see what remains to be done.",
    author: "Marie Curie",
    role: "Physicist & Chemist, Nobel Laureate",
    imageUrl: "",
    gradient: "from-green-400 to-cyan-600",
    emoji: "☢️",
  },

  // === EMMELINE PANKHURST ===
  {
    text: "Deeds, not words.",
    author: "Emmeline Pankhurst",
    role: "Suffragette Leader",
    imageUrl: "",
    gradient: "from-violet-400 to-violet-600",
    emoji: "🟣",
  },
  {
    text: "We are here, not because we are law-breakers; we are here in our efforts to become law-makers.",
    author: "Emmeline Pankhurst",
    role: "Suffragette Leader",
    imageUrl: "",
    gradient: "from-purple-400 to-fuchsia-600",
    emoji: "🏳️",
  },
  {
    text: "I would rather be a rebel than a slave.",
    author: "Emmeline Pankhurst",
    role: "Suffragette Leader",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-violet-600",
    emoji: "🪧",
  },

  // === ELEANOR ROOSEVELT ===
  {
    text: "No one can make you feel inferior without your consent.",
    author: "Eleanor Roosevelt",
    role: "First Lady & Human Rights Advocate",
    imageUrl: "",
    gradient: "from-blue-400 to-violet-600",
    emoji: "🕊️",
  },
  {
    text: "Do one thing every day that scares you.",
    author: "Eleanor Roosevelt",
    role: "First Lady & Human Rights Advocate",
    imageUrl: "",
    gradient: "from-indigo-400 to-violet-600",
    emoji: "🌍",
  },
  {
    text: "The future belongs to those who believe in the beauty of their dreams.",
    author: "Eleanor Roosevelt",
    role: "First Lady & Human Rights Advocate",
    imageUrl: "",
    gradient: "from-violet-400 to-blue-600",
    emoji: "🌈",
  },
  {
    text: "You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face.",
    author: "Eleanor Roosevelt",
    role: "First Lady & Human Rights Advocate",
    imageUrl: "",
    gradient: "from-sky-400 to-violet-600",
    emoji: "💫",
  },
  {
    text: "A woman is like a tea bag; you never know how strong it is until it's in hot water.",
    author: "Eleanor Roosevelt",
    role: "First Lady & Human Rights Advocate",
    imageUrl: "",
    gradient: "from-cyan-400 to-blue-600",
    emoji: "🫖",
  },

  // === ROSA PARKS ===
  {
    text: "I have learned over the years that when one's mind is made up, this diminishes fear.",
    author: "Rosa Parks",
    role: "Civil Rights Activist",
    imageUrl: "",
    gradient: "from-amber-400 to-rose-600",
    emoji: "🚌",
  },
  {
    text: "Each person must live their life as a model for others.",
    author: "Rosa Parks",
    role: "Civil Rights Activist",
    imageUrl: "",
    gradient: "from-red-400 to-amber-600",
    emoji: "✊",
  },
  {
    text: "I would like to be remembered as a person who wanted to be free.",
    author: "Rosa Parks",
    role: "Civil Rights Activist",
    imageUrl: "",
    gradient: "from-orange-400 to-rose-600",
    emoji: "🗽",
  },

  // === SIMONE DE BEAUVOIR ===
  {
    text: "One is not born, but rather becomes, a woman.",
    author: "Simone de Beauvoir",
    role: "Philosopher & Writer",
    imageUrl: "",
    gradient: "from-slate-400 to-slate-600",
    emoji: "📝",
  },
  {
    text: "Change your life today. Don't gamble on the future, act now, without delay.",
    author: "Simone de Beauvoir",
    role: "Philosopher & Writer",
    imageUrl: "",
    gradient: "from-gray-400 to-slate-600",
    emoji: "🗝️",
  },
  {
    text: "I am too intelligent, too demanding, and too resourceful for anyone to be able to take charge of me entirely.",
    author: "Simone de Beauvoir",
    role: "Philosopher & Writer",
    imageUrl: "",
    gradient: "from-zinc-400 to-gray-600",
    emoji: "🎓",
  },

  // === FRIDA KAHLO ===
  {
    text: "Feet, what do I need you for when I have wings to fly?",
    author: "Frida Kahlo",
    role: "Artist",
    imageUrl: "",
    gradient: "from-red-400 to-orange-600",
    emoji: "🎨",
  },
  {
    text: "I paint flowers so they will not die.",
    author: "Frida Kahlo",
    role: "Artist",
    imageUrl: "",
    gradient: "from-yellow-400 to-red-600",
    emoji: "🌺",
  },
  {
    text: "I used to think I was the strangest person in the world but then I thought there are so many people in the world, there must be someone just like me.",
    author: "Frida Kahlo",
    role: "Artist",
    imageUrl: "",
    gradient: "from-pink-400 to-orange-600",
    emoji: "🖌️",
  },
  {
    text: "At the end of the day, we can endure much more than we think we can.",
    author: "Frida Kahlo",
    role: "Artist",
    imageUrl: "",
    gradient: "from-rose-400 to-yellow-600",
    emoji: "🌻",
  },

  // === COCO CHANEL ===
  {
    text: "A girl should be two things: who and what she wants.",
    author: "Coco Chanel",
    role: "Fashion Designer",
    imageUrl: "",
    gradient: "from-stone-400 to-stone-600",
    emoji: "👗",
  },
  {
    text: "The most courageous act is still to think for yourself. Aloud.",
    author: "Coco Chanel",
    role: "Fashion Designer",
    imageUrl: "",
    gradient: "from-neutral-400 to-stone-600",
    emoji: "💄",
  },
  {
    text: "In order to be irreplaceable one must always be different.",
    author: "Coco Chanel",
    role: "Fashion Designer",
    imageUrl: "",
    gradient: "from-zinc-400 to-neutral-600",
    emoji: "✂️",
  },
  {
    text: "Elegance is when the inside is as beautiful as the outside.",
    author: "Coco Chanel",
    role: "Fashion Designer",
    imageUrl: "",
    gradient: "from-amber-400 to-stone-600",
    emoji: "🪞",
  },

  // === JOSEPHINE BAKER ===
  {
    text: "I wasn't really naked. I simply didn't have any clothes on.",
    author: "Josephine Baker",
    role: "Entertainer & Civil Rights Activist",
    imageUrl: "",
    gradient: "from-yellow-400 to-pink-600",
    emoji: "💃",
  },
  {
    text: "I have walked into the palaces of kings and queens and into the houses of presidents. But I could not walk into a hotel in America and get a cup of coffee.",
    author: "Josephine Baker",
    role: "Entertainer & Civil Rights Activist",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-amber-600",
    emoji: "🎭",
  },
  {
    text: "All my life, I have maintained that the people of the world can learn to live together in peace.",
    author: "Josephine Baker",
    role: "Entertainer & Civil Rights Activist",
    imageUrl: "",
    gradient: "from-pink-400 to-yellow-600",
    emoji: "🌍",
  },

  // === HELEN KELLER ===
  {
    text: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
    author: "Helen Keller",
    role: "Author & Disability Rights Advocate",
    imageUrl: "",
    gradient: "from-sky-400 to-emerald-600",
    emoji: "💛",
  },
  {
    text: "Alone we can do so little; together we can do so much.",
    author: "Helen Keller",
    role: "Author & Disability Rights Advocate",
    imageUrl: "",
    gradient: "from-teal-400 to-sky-600",
    emoji: "🤲",
  },
  {
    text: "Life is either a daring adventure or nothing at all.",
    author: "Helen Keller",
    role: "Author & Disability Rights Advocate",
    imageUrl: "",
    gradient: "from-emerald-400 to-sky-600",
    emoji: "🌊",
  },
  {
    text: "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.",
    author: "Helen Keller",
    role: "Author & Disability Rights Advocate",
    imageUrl: "",
    gradient: "from-green-400 to-blue-600",
    emoji: "☀️",
  },
  {
    text: "Keep your face to the sunshine and you cannot see a shadow.",
    author: "Helen Keller",
    role: "Author & Disability Rights Advocate",
    imageUrl: "",
    gradient: "from-yellow-400 to-emerald-600",
    emoji: "🌞",
  },

  // === ANNE SULLIVAN ===
  {
    text: "Children require guidance and sympathy far more than instruction.",
    author: "Anne Sullivan",
    role: "Educator & Helen Keller's Teacher",
    imageUrl: "",
    gradient: "from-orange-400 to-teal-600",
    emoji: "🍎",
  },
  {
    text: "Keep on beginning and failing. Each time you fail, start all over again, and you will grow stronger.",
    author: "Anne Sullivan",
    role: "Educator & Helen Keller's Teacher",
    imageUrl: "",
    gradient: "from-teal-400 to-orange-600",
    emoji: "📝",
  },

  // === GERTRUDE STEIN ===
  {
    text: "A rose is a rose is a rose.",
    author: "Gertrude Stein",
    role: "Writer & Art Collector",
    imageUrl: "",
    gradient: "from-rose-400 to-fuchsia-600",
    emoji: "🌹",
  },
  {
    text: "Everybody gets so much information all day long that they lose their common sense.",
    author: "Gertrude Stein",
    role: "Writer & Art Collector",
    imageUrl: "",
    gradient: "from-purple-400 to-rose-600",
    emoji: "🖼️",
  },
  {
    text: "You look ridiculous if you dance. You look ridiculous if you don't dance. So you might as well dance.",
    author: "Gertrude Stein",
    role: "Writer & Art Collector",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-purple-600",
    emoji: "🎪",
  },

  // === DOROTHY PARKER ===
  {
    text: "The cure for boredom is curiosity. There is no cure for curiosity.",
    author: "Dorothy Parker",
    role: "Poet, Writer & Critic",
    imageUrl: "",
    gradient: "from-red-400 to-violet-600",
    emoji: "🍸",
  },
  {
    text: "Living well is the best revenge.",
    author: "Dorothy Parker",
    role: "Poet, Writer & Critic",
    imageUrl: "",
    gradient: "from-violet-400 to-red-600",
    emoji: "🥀",
  },
  {
    text: "I don't care what is written about me so long as it isn't true.",
    author: "Dorothy Parker",
    role: "Poet, Writer & Critic",
    imageUrl: "",
    gradient: "from-pink-400 to-violet-600",
    emoji: "✒️",
  },
  {
    text: "The first thing I do in the morning is brush my teeth and sharpen my tongue.",
    author: "Dorothy Parker",
    role: "Poet, Writer & Critic",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-red-600",
    emoji: "🗞️",
  },

  // === SACAGAWEA & POCAHONTAS ===
  {
    text: "Everything I do is for my people.",
    author: "Sacagawea",
    role: "Lemhi Shoshone Guide & Interpreter",
    imageUrl: "",
    gradient: "from-green-400 to-amber-600",
    emoji: "🏔️",
  },
  {
    text: "If you would but know the end of your own passions, you would not trouble us.",
    author: "Pocahontas (attributed)",
    role: "Powhatan Mediator",
    imageUrl: "",
    gradient: "from-amber-400 to-green-600",
    emoji: "🌾",
  },

  // === NEFERTITI ===
  {
    text: "One who is content with what he has is the richest in the world.",
    author: "Nefertiti (attributed)",
    role: "Queen of Egypt",
    imageUrl: "",
    gradient: "from-yellow-400 to-amber-600",
    emoji: "☥",
  },

  // === MORE ELEANOR ROOSEVELT ===
  {
    text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
    author: "Eleanor Roosevelt",
    role: "First Lady & Human Rights Advocate",
    imageUrl: "",
    gradient: "from-blue-400 to-emerald-600",
    emoji: "💡",
  },

  // === ADDITIONAL ===
  {
    text: "Life is not easy for any of us. But what of that? We must have perseverance and above all confidence in ourselves.",
    author: "Marie Curie",
    role: "Physicist & Chemist, Nobel Laureate",
    imageUrl: "",
    gradient: "from-teal-400 to-emerald-600",
    emoji: "🧬",
  },
  {
    text: "Although the world is full of suffering, it is full also of the overcoming of it.",
    author: "Helen Keller",
    role: "Author & Disability Rights Advocate",
    imageUrl: "",
    gradient: "from-lime-400 to-emerald-600",
    emoji: "🦋",
  },
];
