import { Quote } from '../types';

export const indianQuotes: Quote[] = [
  // === FREEDOM FIGHTERS & POLITICAL LEADERS ===
  {
    text: "We want deeper sincerity of motive, a greater courage in speech and earnestness in action.",
    author: "Sarojini Naidu",
    role: "Poet & Freedom Fighter",
    imageUrl: "",
    gradient: "from-orange-400 to-red-600",
    emoji: "🪷",
  },
  {
    text: "A country's greatness lies in its undying ideals of love and sacrifice that inspire the mothers of the race.",
    author: "Sarojini Naidu",
    role: "Poet & Freedom Fighter",
    imageUrl: "",
    gradient: "from-amber-400 to-orange-600",
    emoji: "🇮🇳",
  },
  {
    text: "When there is oppression, the only self-respecting thing is to rise and say this shall cease today, because my right is justice.",
    author: "Sarojini Naidu",
    role: "Poet & Freedom Fighter",
    imageUrl: "",
    gradient: "from-rose-400 to-red-600",
    emoji: "🔥",
  },
  {
    text: "You cannot shake hands with a clenched fist.",
    author: "Indira Gandhi",
    role: "Former Prime Minister of India",
    imageUrl: "",
    gradient: "from-blue-400 to-indigo-600",
    emoji: "🇮🇳",
  },
  {
    text: "The power to question is the basis of all human progress.",
    author: "Indira Gandhi",
    role: "Former Prime Minister of India",
    imageUrl: "",
    gradient: "from-indigo-400 to-purple-600",
    emoji: "🪷",
  },
  {
    text: "There are two kinds of people, those who do the work and those who take the credit. Try to be in the first group; there is less competition there.",
    author: "Indira Gandhi",
    role: "Former Prime Minister of India",
    imageUrl: "",
    gradient: "from-violet-400 to-purple-600",
    emoji: "🏛️",
  },
  {
    text: "My grandfather once told me that there were two kinds of people: those who do the work and those who take the credit. He told me to try to be in the first group; there was much less competition.",
    author: "Indira Gandhi",
    role: "Former Prime Minister of India",
    imageUrl: "",
    gradient: "from-sky-400 to-blue-600",
    emoji: "🇮🇳",
  },
  {
    text: "I am the daughter of a great father. I am not just a politician. I am an Indian woman.",
    author: "Sushma Swaraj",
    role: "Former External Affairs Minister",
    imageUrl: "",
    gradient: "from-orange-400 to-amber-600",
    emoji: "🇮🇳",
  },
  {
    text: "Diplomacy is not about being soft. It is about being effective.",
    author: "Sushma Swaraj",
    role: "Former External Affairs Minister",
    imageUrl: "",
    gradient: "from-teal-400 to-cyan-600",
    emoji: "🏛️",
  },
  {
    text: "I am not scared of anyone. I will not let anybody's daughter suffer.",
    author: "Sushma Swaraj",
    role: "Former External Affairs Minister",
    imageUrl: "",
    gradient: "from-red-400 to-rose-600",
    emoji: "🔥",
  },
  {
    text: "I am a woman above everything else.",
    author: "Rani Lakshmibai",
    role: "Queen of Jhansi & Freedom Fighter",
    imageUrl: "",
    gradient: "from-amber-500 to-red-600",
    emoji: "⚔️",
  },
  {
    text: "If you are strong enough, there are no precedents.",
    author: "Nirmala Sitharaman",
    role: "Finance Minister of India",
    imageUrl: "",
    gradient: "from-emerald-400 to-teal-600",
    emoji: "🇮🇳",
  },
  {
    text: "India needs a strong and stable government.",
    author: "Sonia Gandhi",
    role: "Political Leader",
    imageUrl: "",
    gradient: "from-blue-400 to-sky-600",
    emoji: "🏛️",
  },

  // === SPACE & SCIENCE ===
  {
    text: "The path from dreams to success does exist. May you have the vision to find it, the courage to get on to it, and the perseverance to follow it.",
    author: "Kalpana Chawla",
    role: "NASA Astronaut",
    imageUrl: "",
    gradient: "from-purple-400 to-indigo-600",
    emoji: "🚀",
  },
  {
    text: "You are just your intelligence.",
    author: "Kalpana Chawla",
    role: "NASA Astronaut",
    imageUrl: "",
    gradient: "from-indigo-400 to-blue-600",
    emoji: "🌌",
  },
  {
    text: "Do something you really love and it will take you where you want to go.",
    author: "Kalpana Chawla",
    role: "NASA Astronaut",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-purple-600",
    emoji: "🚀",
  },
  {
    text: "When you look at the stars and the galaxy, you feel that you are not just from any particular piece of land, but from the solar system.",
    author: "Kalpana Chawla",
    role: "NASA Astronaut",
    imageUrl: "",
    gradient: "from-blue-500 to-violet-600",
    emoji: "🌌",
  },
  {
    text: "Once you dream, you have to believe in it and work hard for it.",
    author: "Sunita Williams",
    role: "NASA Astronaut",
    imageUrl: "",
    gradient: "from-cyan-400 to-blue-600",
    emoji: "🚀",
  },
  {
    text: "If you dream of something, go out there and do it.",
    author: "Sunita Williams",
    role: "NASA Astronaut",
    imageUrl: "",
    gradient: "from-sky-400 to-indigo-600",
    emoji: "🌌",
  },
  {
    text: "Being an engineer is a wonderful profession. You can see the results of your hard work.",
    author: "Tessy Thomas",
    role: "Missile Scientist, 'Missile Woman of India'",
    imageUrl: "",
    gradient: "from-orange-400 to-red-600",
    emoji: "🔬",
  },
  {
    text: "There is no gender discrimination in science. What matters is your dedication.",
    author: "Tessy Thomas",
    role: "Missile Scientist, 'Missile Woman of India'",
    imageUrl: "",
    gradient: "from-rose-400 to-pink-600",
    emoji: "🚀",
  },

  // === MUSIC & ARTS ===
  {
    text: "My voice is my identity. If I can sing, I can do anything.",
    author: "Lata Mangeshkar",
    role: "Legendary Playback Singer",
    imageUrl: "",
    gradient: "from-pink-400 to-rose-600",
    emoji: "🎵",
  },
  {
    text: "In my entire career, I have been very particular about one thing — the quality of my work.",
    author: "Lata Mangeshkar",
    role: "Legendary Playback Singer",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-pink-600",
    emoji: "🎶",
  },
  {
    text: "I believe in hard work. The only shortcut to success is through hard work.",
    author: "Lata Mangeshkar",
    role: "Legendary Playback Singer",
    imageUrl: "",
    gradient: "from-rose-400 to-fuchsia-600",
    emoji: "🎵",
  },
  {
    text: "Competition is always a good thing. It forces us to do our best.",
    author: "Asha Bhosle",
    role: "Legendary Playback Singer",
    imageUrl: "",
    gradient: "from-amber-400 to-yellow-600",
    emoji: "🎶",
  },
  {
    text: "Age is just a number, and I believe in living life to the fullest at every stage.",
    author: "Asha Bhosle",
    role: "Legendary Playback Singer",
    imageUrl: "",
    gradient: "from-yellow-400 to-orange-600",
    emoji: "🎵",
  },
  {
    text: "Music is the highest form of worship. Through music, we can reach the divine.",
    author: "M.S. Subbulakshmi",
    role: "Carnatic Vocalist & Bharat Ratna Awardee",
    imageUrl: "",
    gradient: "from-orange-400 to-amber-600",
    emoji: "🪷",
  },
  {
    text: "I have always believed that music transcends all barriers of language and geography.",
    author: "M.S. Subbulakshmi",
    role: "Carnatic Vocalist & Bharat Ratna Awardee",
    imageUrl: "",
    gradient: "from-red-400 to-orange-600",
    emoji: "🎵",
  },

  // === LAW ENFORCEMENT & ADVENTURE ===
  {
    text: "We should not give up and we should not allow the problem to defeat us.",
    author: "Kiran Bedi",
    role: "First Female IPS Officer",
    imageUrl: "",
    gradient: "from-emerald-400 to-green-600",
    emoji: "🇮🇳",
  },
  {
    text: "I was not born with a silver spoon. Whatever I have achieved, I have achieved through hard work.",
    author: "Kiran Bedi",
    role: "First Female IPS Officer",
    imageUrl: "",
    gradient: "from-green-400 to-teal-600",
    emoji: "🏅",
  },
  {
    text: "The summit is what drives us, but the climb itself is what matters.",
    author: "Bachendri Pal",
    role: "First Indian Woman to Summit Everest",
    imageUrl: "",
    gradient: "from-sky-400 to-cyan-600",
    emoji: "🏔️",
  },
  {
    text: "Mountains teach you that you are not as strong as you think, but much stronger than you imagine.",
    author: "Bachendri Pal",
    role: "First Indian Woman to Summit Everest",
    imageUrl: "",
    gradient: "from-cyan-400 to-teal-600",
    emoji: "🏔️",
  },
  {
    text: "Losing a leg has not stopped me from climbing. Losing hope would have.",
    author: "Arunima Sinha",
    role: "First Female Amputee to Climb Everest",
    imageUrl: "",
    gradient: "from-teal-400 to-emerald-600",
    emoji: "🏔️",
  },
  {
    text: "People told me I could not do it. That became my biggest motivation.",
    author: "Arunima Sinha",
    role: "First Female Amputee to Climb Everest",
    imageUrl: "",
    gradient: "from-lime-400 to-green-600",
    emoji: "🔥",
  },

  // === BUSINESS & ENTREPRENEURSHIP ===
  {
    text: "Be compassionate and never think you are better than anyone.",
    author: "Sudha Murty",
    role: "Author & Philanthropist",
    imageUrl: "",
    gradient: "from-yellow-400 to-amber-600",
    emoji: "🪷",
  },
  {
    text: "Money can buy many things but it cannot buy the most important — happiness.",
    author: "Sudha Murty",
    role: "Author & Philanthropist",
    imageUrl: "",
    gradient: "from-orange-400 to-yellow-600",
    emoji: "📚",
  },
  {
    text: "No matter how big you become in life, never look down upon anyone.",
    author: "Sudha Murty",
    role: "Author & Philanthropist",
    imageUrl: "",
    gradient: "from-amber-400 to-orange-600",
    emoji: "🪷",
  },
  {
    text: "Experience is the best teacher. If you get the lesson, it doesn't matter if you fail.",
    author: "Sudha Murty",
    role: "Author & Philanthropist",
    imageUrl: "",
    gradient: "from-rose-400 to-amber-600",
    emoji: "📖",
  },
  {
    text: "I was constantly told that I was in the wrong place. But I stayed on.",
    author: "Kiran Mazumdar-Shaw",
    role: "Founder, Biocon Limited",
    imageUrl: "",
    gradient: "from-emerald-400 to-cyan-600",
    emoji: "🔬",
  },
  {
    text: "Risk-taking is the essence of innovation. You cannot discover anything new if you don't take risks.",
    author: "Kiran Mazumdar-Shaw",
    role: "Founder, Biocon Limited",
    imageUrl: "",
    gradient: "from-teal-400 to-blue-600",
    emoji: "💡",
  },
  {
    text: "Being an entrepreneur is my dharma — it is what I was meant to do.",
    author: "Kiran Mazumdar-Shaw",
    role: "Founder, Biocon Limited",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "🔬",
  },
  {
    text: "Whatever anybody says or does, assume positive intent.",
    author: "Indra Nooyi",
    role: "Former CEO, PepsiCo",
    imageUrl: "",
    gradient: "from-blue-400 to-cyan-600",
    emoji: "🌏",
  },
  {
    text: "Just because you are CEO, don't think you have landed. You must continually increase your learning.",
    author: "Indra Nooyi",
    role: "Former CEO, PepsiCo",
    imageUrl: "",
    gradient: "from-indigo-400 to-sky-600",
    emoji: "💡",
  },
  {
    text: "Leadership is hard to define and good leadership even harder. But if you can get people to follow you to the ends of the earth, you are a great leader.",
    author: "Indra Nooyi",
    role: "Former CEO, PepsiCo",
    imageUrl: "",
    gradient: "from-violet-400 to-indigo-600",
    emoji: "🌏",
  },
  {
    text: "I'm a very driven person. I challenge the status quo.",
    author: "Indra Nooyi",
    role: "Former CEO, PepsiCo",
    imageUrl: "",
    gradient: "from-purple-400 to-blue-600",
    emoji: "🔥",
  },
  {
    text: "I believe in the power of disruption. We broke the myth that beauty products could only be sold offline in India.",
    author: "Falguni Nayar",
    role: "Founder & CEO, Nykaa",
    imageUrl: "",
    gradient: "from-pink-400 to-fuchsia-600",
    emoji: "💄",
  },
  {
    text: "It is never too late to chase your dreams. I started my entrepreneurial journey at fifty.",
    author: "Falguni Nayar",
    role: "Founder & CEO, Nykaa",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-rose-600",
    emoji: "💡",
  },

  // === SPORTS ===
  {
    text: "I always tried to turn every disaster into an opportunity.",
    author: "P.T. Usha",
    role: "Track & Field Legend, 'Payyoli Express'",
    imageUrl: "",
    gradient: "from-red-400 to-orange-600",
    emoji: "🏃‍♀️",
  },
  {
    text: "Winning and losing is part of life. What matters is you give your best.",
    author: "P.T. Usha",
    role: "Track & Field Legend, 'Payyoli Express'",
    imageUrl: "",
    gradient: "from-orange-400 to-red-600",
    emoji: "🏅",
  },
  {
    text: "I don't want to be called brave. I just want to be remembered as a fighter.",
    author: "Mary Kom",
    role: "World Champion Boxer",
    imageUrl: "",
    gradient: "from-red-400 to-rose-600",
    emoji: "🥊",
  },
  {
    text: "Do not say you are weak because you are a woman.",
    author: "Mary Kom",
    role: "World Champion Boxer",
    imageUrl: "",
    gradient: "from-rose-400 to-red-600",
    emoji: "🥊",
  },
  {
    text: "My success has come from not giving up, even when the odds were against me.",
    author: "Mary Kom",
    role: "World Champion Boxer",
    imageUrl: "",
    gradient: "from-amber-400 to-red-600",
    emoji: "🏅",
  },
  {
    text: "Winning the Olympic medal was a dream come true, but the journey taught me more than the destination.",
    author: "P.V. Sindhu",
    role: "Olympic Badminton Champion",
    imageUrl: "",
    gradient: "from-yellow-400 to-orange-600",
    emoji: "🏸",
  },
  {
    text: "Every match I play, I play for my country. That feeling never gets old.",
    author: "P.V. Sindhu",
    role: "Olympic Badminton Champion",
    imageUrl: "",
    gradient: "from-blue-400 to-indigo-600",
    emoji: "🇮🇳",
  },
  {
    text: "Pressure is a privilege. It means you are doing something that matters.",
    author: "Saina Nehwal",
    role: "Olympic Badminton Medalist",
    imageUrl: "",
    gradient: "from-emerald-400 to-teal-600",
    emoji: "🏸",
  },
  {
    text: "Consistency is the key. One win doesn't make you a champion; consistency does.",
    author: "Saina Nehwal",
    role: "Olympic Badminton Medalist",
    imageUrl: "",
    gradient: "from-teal-400 to-green-600",
    emoji: "🏅",
  },
  {
    text: "I run for my country. Every stride I take is for India.",
    author: "Hima Das",
    role: "Sprinter, 'Dhing Express'",
    imageUrl: "",
    gradient: "from-orange-400 to-amber-600",
    emoji: "🏃‍♀️",
  },
  {
    text: "Miracles happen on the court when you forget everything and just play.",
    author: "Sania Mirza",
    role: "Tennis Champion",
    imageUrl: "",
    gradient: "from-green-400 to-cyan-600",
    emoji: "🎾",
  },
  {
    text: "Being number one is not just about the ranking. It's about the respect you earn.",
    author: "Sania Mirza",
    role: "Tennis Champion",
    imageUrl: "",
    gradient: "from-lime-400 to-emerald-600",
    emoji: "🎾",
  },
  {
    text: "People said women's cricket was not worth watching. We proved them wrong.",
    author: "Mithali Raj",
    role: "Cricket Legend & Former Captain",
    imageUrl: "",
    gradient: "from-blue-400 to-green-600",
    emoji: "🏏",
  },
  {
    text: "I have always believed that as cricketers, we are entertainers first. We are here to inspire.",
    author: "Mithali Raj",
    role: "Cricket Legend & Former Captain",
    imageUrl: "",
    gradient: "from-cyan-400 to-blue-600",
    emoji: "🏏",
  },
  {
    text: "I want young girls to look at me and believe that they too can make it big in sport.",
    author: "Smriti Mandhana",
    role: "International Cricketer",
    imageUrl: "",
    gradient: "from-sky-400 to-blue-600",
    emoji: "🏏",
  },
  {
    text: "When I go out to bat, I want to play my natural game and express myself.",
    author: "Smriti Mandhana",
    role: "International Cricketer",
    imageUrl: "",
    gradient: "from-indigo-400 to-cyan-600",
    emoji: "🏏",
  },

  // === LITERATURE & WRITING ===
  {
    text: "I divided my life into two parts. One part I gave to my writing and the other part I gave to the one I loved.",
    author: "Amrita Pritam",
    role: "Poet & Author",
    imageUrl: "",
    gradient: "from-purple-400 to-pink-600",
    emoji: "📖",
  },
  {
    text: "Every woman is a story. Every story is a woman.",
    author: "Amrita Pritam",
    role: "Poet & Author",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-purple-600",
    emoji: "✍️",
  },
  {
    text: "I write because I cannot not write. It is not a choice. It is a compulsion.",
    author: "Kamala Das",
    role: "Poet & Author",
    imageUrl: "",
    gradient: "from-rose-400 to-purple-600",
    emoji: "📖",
  },
  {
    text: "A woman who writes has power, and a woman with power is feared.",
    author: "Kamala Das",
    role: "Poet & Author",
    imageUrl: "",
    gradient: "from-pink-400 to-violet-600",
    emoji: "✍️",
  },
  {
    text: "I have always fought for the voiceless. Literature is the voice of the oppressed.",
    author: "Mahasweta Devi",
    role: "Author & Social Activist",
    imageUrl: "",
    gradient: "from-amber-400 to-red-600",
    emoji: "📚",
  },
  {
    text: "My writing is my resistance. I write so that the struggles of the marginalized are never forgotten.",
    author: "Mahasweta Devi",
    role: "Author & Social Activist",
    imageUrl: "",
    gradient: "from-orange-400 to-rose-600",
    emoji: "🔥",
  },
  {
    text: "It is the duty of a writer to raise a voice against injustice.",
    author: "Ismat Chughtai",
    role: "Urdu Author & Feminist Writer",
    imageUrl: "",
    gradient: "from-red-400 to-amber-600",
    emoji: "✍️",
  },
  {
    text: "Why should women suppress their desires? We are human beings, not statues.",
    author: "Ismat Chughtai",
    role: "Urdu Author & Feminist Writer",
    imageUrl: "",
    gradient: "from-pink-400 to-red-600",
    emoji: "🔥",
  },
  {
    text: "The God of Small Things is about the ways in which the small things in life affect us the most.",
    author: "Arundhati Roy",
    role: "Booker Prize-Winning Author",
    imageUrl: "",
    gradient: "from-emerald-400 to-lime-600",
    emoji: "📚",
  },
  {
    text: "To never claim to know a place fully is the first step to understanding it.",
    author: "Jhumpa Lahiri",
    role: "Pulitzer Prize-Winning Author",
    imageUrl: "",
    gradient: "from-teal-400 to-cyan-600",
    emoji: "📖",
  },
  {
    text: "I was never a rebel. I just said things that needed to be said — only a little louder than others.",
    author: "Shobhaa De",
    role: "Author & Columnist",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-pink-600",
    emoji: "✍️",
  },
  {
    text: "Indian women are not weak. They never were. The world is just now beginning to see what we always knew.",
    author: "Shobhaa De",
    role: "Author & Columnist",
    imageUrl: "",
    gradient: "from-rose-400 to-fuchsia-600",
    emoji: "🇮🇳",
  },

  // === SOCIAL REFORM ===
  {
    text: "A good education is a stepping stone to a brighter future. Without it, we remain in darkness.",
    author: "Savitribai Phule",
    role: "Social Reformer & India's First Female Teacher",
    imageUrl: "",
    gradient: "from-yellow-400 to-orange-600",
    emoji: "📖",
  },
  {
    text: "Go, get education. Be self-reliant, be industrious. Work — that is the way to uplift our people.",
    author: "Savitribai Phule",
    role: "Social Reformer & India's First Female Teacher",
    imageUrl: "",
    gradient: "from-amber-400 to-yellow-600",
    emoji: "🪷",
  },
  {
    text: "Education is the key to the emancipation of women. Without it, liberation is impossible.",
    author: "Pandita Ramabai",
    role: "Scholar & Social Reformer",
    imageUrl: "",
    gradient: "from-orange-400 to-amber-600",
    emoji: "📚",
  },
  {
    text: "The condition of women in India will improve only when women themselves fight for their rights.",
    author: "Pandita Ramabai",
    role: "Scholar & Social Reformer",
    imageUrl: "",
    gradient: "from-red-400 to-orange-600",
    emoji: "🔥",
  },

  // === MOTHER TERESA ===
  {
    text: "If you judge people, you have no time to love them.",
    author: "Mother Teresa",
    role: "Humanitarian & Nobel Laureate (adopted Indian)",
    imageUrl: "",
    gradient: "from-sky-400 to-blue-600",
    emoji: "🪷",
  },
  {
    text: "Not all of us can do great things. But we can do small things with great love.",
    author: "Mother Teresa",
    role: "Humanitarian & Nobel Laureate (adopted Indian)",
    imageUrl: "",
    gradient: "from-blue-400 to-sky-600",
    emoji: "🕊️",
  },
  {
    text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
    author: "Mother Teresa",
    role: "Humanitarian & Nobel Laureate (adopted Indian)",
    imageUrl: "",
    gradient: "from-cyan-400 to-sky-600",
    emoji: "🪷",
  },
  {
    text: "I alone cannot change the world, but I can cast a stone across the waters to create many ripples.",
    author: "Mother Teresa",
    role: "Humanitarian & Nobel Laureate (adopted Indian)",
    imageUrl: "",
    gradient: "from-indigo-400 to-blue-600",
    emoji: "🕊️",
  },
  {
    text: "Peace begins with a smile.",
    author: "Mother Teresa",
    role: "Humanitarian & Nobel Laureate (adopted Indian)",
    imageUrl: "",
    gradient: "from-violet-400 to-sky-600",
    emoji: "🕊️",
  },

  // === ACTIVISTS ===
  {
    text: "Development that displaces people is not development. It is destruction.",
    author: "Medha Patkar",
    role: "Social Activist & Narmada Bachao Leader",
    imageUrl: "",
    gradient: "from-green-400 to-lime-600",
    emoji: "🌿",
  },
  {
    text: "The voice of the displaced must be heard. Their right to life and livelihood is non-negotiable.",
    author: "Medha Patkar",
    role: "Social Activist & Narmada Bachao Leader",
    imageUrl: "",
    gradient: "from-lime-400 to-green-600",
    emoji: "🌏",
  },
  {
    text: "My struggle is not just about politics. It is about the right to life of my people.",
    author: "Irom Sharmila",
    role: "Civil Rights Activist, 'Iron Lady of Manipur'",
    imageUrl: "",
    gradient: "from-teal-400 to-green-600",
    emoji: "🕊️",
  },
  {
    text: "I did not choose this path. This path chose me. But I walked it with my head held high.",
    author: "Irom Sharmila",
    role: "Civil Rights Activist, 'Iron Lady of Manipur'",
    imageUrl: "",
    gradient: "from-emerald-400 to-lime-600",
    emoji: "🔥",
  },
  {
    text: "Seed freedom is the foundation of food freedom. Without it, we are at the mercy of corporations.",
    author: "Vandana Shiva",
    role: "Environmental Activist & Author",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "🌿",
  },
  {
    text: "Earth democracy is based on living economies, living cultures, and living democracies.",
    author: "Vandana Shiva",
    role: "Environmental Activist & Author",
    imageUrl: "",
    gradient: "from-lime-400 to-teal-600",
    emoji: "🌍",
  },
  {
    text: "You are not Atlas carrying the world on your shoulder. It is good to remember that the planet is carrying you.",
    author: "Vandana Shiva",
    role: "Environmental Activist & Author",
    imageUrl: "",
    gradient: "from-emerald-400 to-green-600",
    emoji: "🌿",
  },
  {
    text: "The real currency of life is not money but the relationships we build and the love we share.",
    author: "Sudha Murty",
    role: "Author & Philanthropist",
    imageUrl: "",
    gradient: "from-pink-400 to-amber-600",
    emoji: "🪷",
  },
  {
    text: "I did not come to this world to be mediocre. I came to excel.",
    author: "Mary Kom",
    role: "World Champion Boxer",
    imageUrl: "",
    gradient: "from-red-500 to-orange-600",
    emoji: "🥊",
  },
  {
    text: "My mother told me to always stay humble and work hard. That advice built my career.",
    author: "Hima Das",
    role: "Sprinter, 'Dhing Express'",
    imageUrl: "",
    gradient: "from-yellow-400 to-lime-600",
    emoji: "🏃‍♀️",
  },
  {
    text: "I did not wait for opportunity. I worked until I became one.",
    author: "P.T. Usha",
    role: "Track & Field Legend, 'Payyoli Express'",
    imageUrl: "",
    gradient: "from-amber-400 to-orange-600",
    emoji: "🏅",
  },
  {
    text: "True wealth is not what you have in your bank account but what you have in your heart.",
    author: "Sudha Murty",
    role: "Author & Philanthropist",
    imageUrl: "",
    gradient: "from-yellow-400 to-rose-600",
    emoji: "📖",
  },
  {
    text: "Forgiveness is a virtue of the brave.",
    author: "Indira Gandhi",
    role: "Former Prime Minister of India",
    imageUrl: "",
    gradient: "from-slate-400 to-blue-600",
    emoji: "🇮🇳",
  },
  {
    text: "I believe in innovation, and the way you get innovation is you fund research and you learn the basic facts.",
    author: "Kiran Mazumdar-Shaw",
    role: "Founder, Biocon Limited",
    imageUrl: "",
    gradient: "from-cyan-400 to-emerald-600",
    emoji: "🔬",
  },
];
