import { Quote } from '../types';

export const poetQuotes: Quote[] = [
  // Maya Angelou (1-6)
  {
    text: "There is no greater agony than bearing an untold story inside you.",
    author: "Maya Angelou",
    role: "Poet & Memoirist",
    imageUrl: "",
    gradient: "from-amber-400 to-orange-600",
    emoji: "🦋",
  },
  {
    text: "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.",
    author: "Maya Angelou",
    role: "Poet & Memoirist",
    imageUrl: "",
    gradient: "from-rose-400 to-pink-600",
    emoji: "🌹",
  },
  {
    text: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
    author: "Maya Angelou",
    role: "Poet & Memoirist",
    imageUrl: "",
    gradient: "from-violet-400 to-purple-600",
    emoji: "💜",
  },
  {
    text: "If you're always trying to be normal you will never know how amazing you can be.",
    author: "Maya Angelou",
    role: "Poet & Memoirist",
    imageUrl: "",
    gradient: "from-sky-400 to-blue-600",
    emoji: "✨",
  },
  {
    text: "A woman's heart should be so hidden in God that a man has to seek Him just to find her.",
    author: "Maya Angelou",
    role: "Poet & Memoirist",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-pink-600",
    emoji: "🕊️",
  },
  {
    text: "I love to see a young girl go out and grab the world by the lapels. Life's a bitch. You've got to go out and kick ass.",
    author: "Maya Angelou",
    role: "Poet & Memoirist",
    imageUrl: "",
    gradient: "from-red-400 to-rose-600",
    emoji: "🔥",
  },

  // Emily Dickinson (7-11)
  {
    text: "If I can stop one heart from breaking, I shall not live in vain.",
    author: "Emily Dickinson",
    role: "Poet",
    imageUrl: "",
    gradient: "from-emerald-400 to-teal-600",
    emoji: "🌿",
  },
  {
    text: "Forever is composed of nows.",
    author: "Emily Dickinson",
    role: "Poet",
    imageUrl: "",
    gradient: "from-indigo-400 to-blue-600",
    emoji: "⏳",
  },
  {
    text: "That it will never come again is what makes life so sweet.",
    author: "Emily Dickinson",
    role: "Poet",
    imageUrl: "",
    gradient: "from-cyan-400 to-teal-600",
    emoji: "🍃",
  },
  {
    text: "I dwell in Possibility.",
    author: "Emily Dickinson",
    role: "Poet",
    imageUrl: "",
    gradient: "from-purple-400 to-violet-600",
    emoji: "🏡",
  },
  {
    text: "Hope is the thing with feathers that perches in the soul.",
    author: "Emily Dickinson",
    role: "Poet",
    imageUrl: "",
    gradient: "from-yellow-400 to-amber-600",
    emoji: "🪶",
  },

  // Sylvia Plath (12-15)
  {
    text: "I took a deep breath and listened to the old brag of my heart. I am, I am, I am.",
    author: "Sylvia Plath",
    role: "Poet & Novelist",
    imageUrl: "",
    gradient: "from-slate-400 to-gray-600",
    emoji: "🖤",
  },
  {
    text: "I am inhabited by a cry. Nightly it flaps out looking, with its hooks, for something to love.",
    author: "Sylvia Plath",
    role: "Poet & Novelist",
    imageUrl: "",
    gradient: "from-zinc-400 to-slate-600",
    emoji: "🌙",
  },
  {
    text: "Perhaps when we find ourselves wanting everything, it is because we are dangerously close to wanting nothing.",
    author: "Sylvia Plath",
    role: "Poet & Novelist",
    imageUrl: "",
    gradient: "from-stone-400 to-neutral-600",
    emoji: "🪞",
  },
  {
    text: "I am made, crudely, for this kind of suffering.",
    author: "Sylvia Plath",
    role: "Poet & Novelist",
    imageUrl: "",
    gradient: "from-red-400 to-gray-600",
    emoji: "🥀",
  },

  // Virginia Woolf (16-20)
  {
    text: "One cannot think well, love well, sleep well, if one has not dined well.",
    author: "Virginia Woolf",
    role: "Novelist & Essayist",
    imageUrl: "",
    gradient: "from-teal-400 to-emerald-600",
    emoji: "📖",
  },
  {
    text: "You cannot find peace by avoiding life.",
    author: "Virginia Woolf",
    role: "Novelist & Essayist",
    imageUrl: "",
    gradient: "from-blue-400 to-indigo-600",
    emoji: "🌊",
  },
  {
    text: "A woman must have money and a room of her own if she is to write fiction.",
    author: "Virginia Woolf",
    role: "Novelist & Essayist",
    imageUrl: "",
    gradient: "from-amber-400 to-yellow-600",
    emoji: "🖊️",
  },
  {
    text: "For most of history, Anonymous was a woman.",
    author: "Virginia Woolf",
    role: "Novelist & Essayist",
    imageUrl: "",
    gradient: "from-rose-400 to-red-600",
    emoji: "📜",
  },
  {
    text: "Lock up your libraries if you like; but there is no gate, no lock, no bolt that you can set upon the freedom of my mind.",
    author: "Virginia Woolf",
    role: "Novelist & Essayist",
    imageUrl: "",
    gradient: "from-violet-400 to-fuchsia-600",
    emoji: "🗝️",
  },

  // Toni Morrison (21-25)
  {
    text: "If there's a book that you want to read, but it hasn't been written yet, then you must write it.",
    author: "Toni Morrison",
    role: "Novelist & Nobel Laureate",
    imageUrl: "",
    gradient: "from-orange-400 to-red-600",
    emoji: "📕",
  },
  {
    text: "You wanna fly, you got to give up the shit that weighs you down.",
    author: "Toni Morrison",
    role: "Novelist & Nobel Laureate",
    imageUrl: "",
    gradient: "from-sky-400 to-cyan-600",
    emoji: "🕊️",
  },
  {
    text: "Freeing yourself was one thing, claiming ownership of that freed self was another.",
    author: "Toni Morrison",
    role: "Novelist & Nobel Laureate",
    imageUrl: "",
    gradient: "from-amber-400 to-orange-600",
    emoji: "🔓",
  },
  {
    text: "If you surrendered to the air, you could ride it.",
    author: "Toni Morrison",
    role: "Novelist & Nobel Laureate",
    imageUrl: "",
    gradient: "from-cyan-400 to-blue-600",
    emoji: "🌬️",
  },
  {
    text: "The function of freedom is to free someone else.",
    author: "Toni Morrison",
    role: "Novelist & Nobel Laureate",
    imageUrl: "",
    gradient: "from-emerald-400 to-green-600",
    emoji: "🗽",
  },

  // Alice Walker (26-28)
  {
    text: "The most common way people give up their power is by thinking they don't have any.",
    author: "Alice Walker",
    role: "Novelist & Poet",
    imageUrl: "",
    gradient: "from-lime-400 to-green-600",
    emoji: "💪",
  },
  {
    text: "In nature, nothing is perfect and everything is perfect.",
    author: "Alice Walker",
    role: "Novelist & Poet",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "🌳",
  },
  {
    text: "Activism is my rent for living on this planet.",
    author: "Alice Walker",
    role: "Novelist & Poet",
    imageUrl: "",
    gradient: "from-teal-400 to-cyan-600",
    emoji: "🌍",
  },

  // Zora Neale Hurston (29-31)
  {
    text: "There are years that ask questions and years that answer.",
    author: "Zora Neale Hurston",
    role: "Novelist & Folklorist",
    imageUrl: "",
    gradient: "from-yellow-400 to-orange-600",
    emoji: "🌻",
  },
  {
    text: "Love makes your soul crawl out from its hiding place.",
    author: "Zora Neale Hurston",
    role: "Novelist & Folklorist",
    imageUrl: "",
    gradient: "from-pink-400 to-rose-600",
    emoji: "💛",
  },
  {
    text: "If you are silent about your pain, they'll kill you and say you enjoyed it.",
    author: "Zora Neale Hurston",
    role: "Novelist & Folklorist",
    imageUrl: "",
    gradient: "from-red-400 to-orange-600",
    emoji: "🗣️",
  },

  // Jane Austen (32-34)
  {
    text: "I declare after all there is no enjoyment like reading!",
    author: "Jane Austen",
    role: "Novelist",
    imageUrl: "",
    gradient: "from-rose-400 to-pink-600",
    emoji: "📚",
  },
  {
    text: "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.",
    author: "Jane Austen",
    role: "Novelist",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-purple-600",
    emoji: "📗",
  },
  {
    text: "There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves; it is not my nature.",
    author: "Jane Austen",
    role: "Novelist",
    imageUrl: "",
    gradient: "from-pink-400 to-fuchsia-600",
    emoji: "💕",
  },

  // Charlotte Bronte (35-37)
  {
    text: "I am no bird; and no net ensnares me: I am a free human being with an independent will.",
    author: "Charlotte Bronte",
    role: "Novelist & Poet",
    imageUrl: "",
    gradient: "from-indigo-400 to-violet-600",
    emoji: "🦅",
  },
  {
    text: "Life appears to me too short to be spent in nursing animosity or registering wrongs.",
    author: "Charlotte Bronte",
    role: "Novelist & Poet",
    imageUrl: "",
    gradient: "from-blue-400 to-sky-600",
    emoji: "⏱️",
  },
  {
    text: "I would always rather be happy than dignified.",
    author: "Charlotte Bronte",
    role: "Novelist & Poet",
    imageUrl: "",
    gradient: "from-amber-400 to-yellow-600",
    emoji: "😊",
  },

  // Emily Bronte (38-39)
  {
    text: "Whatever our souls are made of, his and mine are the same.",
    author: "Emily Bronte",
    role: "Novelist & Poet",
    imageUrl: "",
    gradient: "from-purple-400 to-indigo-600",
    emoji: "💫",
  },
  {
    text: "If I could I would always work in silence and obscurity, and let my efforts be known by their results.",
    author: "Emily Bronte",
    role: "Novelist & Poet",
    imageUrl: "",
    gradient: "from-slate-400 to-blue-600",
    emoji: "🌾",
  },

  // Mary Shelley (40-41)
  {
    text: "Beware; for I am fearless, and therefore powerful.",
    author: "Mary Shelley",
    role: "Novelist",
    imageUrl: "",
    gradient: "from-gray-400 to-zinc-600",
    emoji: "⚡",
  },
  {
    text: "Nothing is so painful to the human mind as a great and sudden change.",
    author: "Mary Shelley",
    role: "Novelist",
    imageUrl: "",
    gradient: "from-neutral-400 to-stone-600",
    emoji: "🌩️",
  },

  // Sappho (42-44)
  {
    text: "What is beautiful is good, and who is good will soon be beautiful.",
    author: "Sappho",
    role: "Ancient Greek Lyric Poet",
    imageUrl: "",
    gradient: "from-amber-400 to-rose-600",
    emoji: "🏛️",
  },
  {
    text: "He is more than a hero, he is a god in my eyes.",
    author: "Sappho",
    role: "Ancient Greek Lyric Poet",
    imageUrl: "",
    gradient: "from-orange-400 to-amber-600",
    emoji: "🏺",
  },
  {
    text: "Some say an army of horsemen, some of foot soldiers, some of ships, is the fairest thing on the black earth, but I say it is what one loves.",
    author: "Sappho",
    role: "Ancient Greek Lyric Poet",
    imageUrl: "",
    gradient: "from-yellow-400 to-red-600",
    emoji: "🫀",
  },

  // Rabia al-Adawiyya (45-46)
  {
    text: "O God! If I worship You for fear of Hell, burn me in Hell, and if I worship You in hope of Paradise, exclude me from Paradise.",
    author: "Rabia al-Adawiyya",
    role: "Sufi Mystic Poet",
    imageUrl: "",
    gradient: "from-emerald-400 to-teal-600",
    emoji: "🕯️",
  },
  {
    text: "I carry a torch in one hand and a bucket of water in the other: with these things I am going to set fire to Heaven and put out the flames of Hell so that voyagers to God can rip the veils and see the real goal.",
    author: "Rabia al-Adawiyya",
    role: "Sufi Mystic Poet",
    imageUrl: "",
    gradient: "from-teal-400 to-green-600",
    emoji: "🪷",
  },

  // Rupi Kaur (47-50)
  {
    text: "You do not just wake up and become the butterfly. Growth is a process.",
    author: "Rupi Kaur",
    role: "Poet & Illustrator",
    imageUrl: "",
    gradient: "from-pink-400 to-rose-600",
    emoji: "🦋",
  },
  {
    text: "What is stronger than the human heart which shatters over and over and still lives.",
    author: "Rupi Kaur",
    role: "Poet & Illustrator",
    imageUrl: "",
    gradient: "from-red-400 to-pink-600",
    emoji: "💗",
  },
  {
    text: "I stand on the sacrifices of a million women before me.",
    author: "Rupi Kaur",
    role: "Poet & Illustrator",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-rose-600",
    emoji: "🌸",
  },
  {
    text: "You must want to spend the rest of your life with yourself first.",
    author: "Rupi Kaur",
    role: "Poet & Illustrator",
    imageUrl: "",
    gradient: "from-violet-400 to-pink-600",
    emoji: "🪞",
  },

  // Amanda Gorman (51-53)
  {
    text: "There is always light, if only we're brave enough to see it. If only we're brave enough to be it.",
    author: "Amanda Gorman",
    role: "Poet & Activist",
    imageUrl: "",
    gradient: "from-yellow-400 to-amber-600",
    emoji: "🌅",
  },
  {
    text: "We are not broken, we are simply unfinished.",
    author: "Amanda Gorman",
    role: "Poet & Activist",
    imageUrl: "",
    gradient: "from-sky-400 to-blue-600",
    emoji: "🌱",
  },
  {
    text: "Words can light fires in the minds of men. Words can wring tears from the hardest hearts.",
    author: "Amanda Gorman",
    role: "Poet & Activist",
    imageUrl: "",
    gradient: "from-orange-400 to-red-600",
    emoji: "🔥",
  },

  // Warsan Shire (54-56)
  {
    text: "No one leaves home unless home is the mouth of a shark.",
    author: "Warsan Shire",
    role: "Poet",
    imageUrl: "",
    gradient: "from-blue-400 to-slate-600",
    emoji: "🌍",
  },
  {
    text: "At the end of the day, it isn't where I came from. Maybe home is somewhere I'm going and never have been before.",
    author: "Warsan Shire",
    role: "Poet",
    imageUrl: "",
    gradient: "from-indigo-400 to-blue-600",
    emoji: "🏠",
  },
  {
    text: "I belong to no one, who belongs to everyone, who has nothing, who wants everything.",
    author: "Warsan Shire",
    role: "Poet",
    imageUrl: "",
    gradient: "from-purple-400 to-indigo-600",
    emoji: "🌌",
  },

  // Adrienne Rich (57-59)
  {
    text: "The moment of change is the only poem.",
    author: "Adrienne Rich",
    role: "Poet & Essayist",
    imageUrl: "",
    gradient: "from-rose-400 to-red-600",
    emoji: "🔄",
  },
  {
    text: "When a woman tells the truth she is creating the possibility for more truth around her.",
    author: "Adrienne Rich",
    role: "Poet & Essayist",
    imageUrl: "",
    gradient: "from-emerald-400 to-green-600",
    emoji: "🌿",
  },
  {
    text: "Lying is done with words, and also with silence.",
    author: "Adrienne Rich",
    role: "Poet & Essayist",
    imageUrl: "",
    gradient: "from-gray-400 to-slate-600",
    emoji: "🤫",
  },

  // Audre Lorde (60-63)
  {
    text: "Your silence will not protect you.",
    author: "Audre Lorde",
    role: "Poet & Activist",
    imageUrl: "",
    gradient: "from-red-400 to-rose-600",
    emoji: "📢",
  },
  {
    text: "When I dare to be powerful, to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.",
    author: "Audre Lorde",
    role: "Poet & Activist",
    imageUrl: "",
    gradient: "from-amber-400 to-red-600",
    emoji: "💪",
  },
  {
    text: "The master's tools will never dismantle the master's house.",
    author: "Audre Lorde",
    role: "Poet & Activist",
    imageUrl: "",
    gradient: "from-orange-400 to-amber-600",
    emoji: "🔨",
  },
  {
    text: "Caring for myself is not self-indulgence, it is self-preservation, and that is an act of political warfare.",
    author: "Audre Lorde",
    role: "Poet & Activist",
    imageUrl: "",
    gradient: "from-pink-400 to-fuchsia-600",
    emoji: "🛡️",
  },

  // Gwendolyn Brooks (64-65)
  {
    text: "We are each other's harvest; we are each other's business; we are each other's magnitude and bond.",
    author: "Gwendolyn Brooks",
    role: "Poet & Pulitzer Laureate",
    imageUrl: "",
    gradient: "from-green-400 to-teal-600",
    emoji: "🌾",
  },
  {
    text: "Art hurts. Art urges voyages - and it is easier to stay at home.",
    author: "Gwendolyn Brooks",
    role: "Poet & Pulitzer Laureate",
    imageUrl: "",
    gradient: "from-violet-400 to-purple-600",
    emoji: "🎨",
  },

  // Elizabeth Bishop (66-67)
  {
    text: "The art of losing isn't hard to master.",
    author: "Elizabeth Bishop",
    role: "Poet & Pulitzer Laureate",
    imageUrl: "",
    gradient: "from-cyan-400 to-sky-600",
    emoji: "🎭",
  },
  {
    text: "All my life I have lived and behaved very much like the sandpiper - just running down the edges of different countries, looking for something.",
    author: "Elizabeth Bishop",
    role: "Poet & Pulitzer Laureate",
    imageUrl: "",
    gradient: "from-blue-400 to-cyan-600",
    emoji: "🐦",
  },

  // Marianne Moore (68-69)
  {
    text: "The cure for loneliness is solitude.",
    author: "Marianne Moore",
    role: "Modernist Poet",
    imageUrl: "",
    gradient: "from-teal-400 to-emerald-600",
    emoji: "🧘",
  },
  {
    text: "Poetry is the art of creating imaginary gardens with real toads in them.",
    author: "Marianne Moore",
    role: "Modernist Poet",
    imageUrl: "",
    gradient: "from-lime-400 to-green-600",
    emoji: "🐸",
  },

  // Kamala Das (70-72)
  {
    text: "It is not your business to worry about tomorrow; you must only love today.",
    author: "Kamala Das",
    role: "Indian Poet & Memoirist",
    imageUrl: "",
    gradient: "from-orange-400 to-rose-600",
    emoji: "🪷",
  },
  {
    text: "Gift him all, gift him what makes you woman, the scent of long hair, the musk of sweat between the breasts.",
    author: "Kamala Das",
    role: "Indian Poet & Memoirist",
    imageUrl: "",
    gradient: "from-red-400 to-fuchsia-600",
    emoji: "🌺",
  },
  {
    text: "I am every woman who seeks love.",
    author: "Kamala Das",
    role: "Indian Poet & Memoirist",
    imageUrl: "",
    gradient: "from-pink-400 to-red-600",
    emoji: "❤️",
  },

  // Amrita Pritam (73-75)
  {
    text: "I will live and die for the things I believe in.",
    author: "Amrita Pritam",
    role: "Punjabi Poet & Novelist",
    imageUrl: "",
    gradient: "from-rose-400 to-amber-600",
    emoji: "🌷",
  },
  {
    text: "Every lover is, in his heart, a madman, and in his head, a minstrel.",
    author: "Amrita Pritam",
    role: "Punjabi Poet & Novelist",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-rose-600",
    emoji: "🎵",
  },
  {
    text: "I searched for my beloved in every corner of the world. How strange that when I found him, he was within me all along.",
    author: "Amrita Pritam",
    role: "Punjabi Poet & Novelist",
    imageUrl: "",
    gradient: "from-purple-400 to-pink-600",
    emoji: "💜",
  },

  // Arundhati Roy (79-81)
  {
    text: "The secret of the Great Stories is that they have no secrets.",
    author: "Arundhati Roy",
    role: "Indian Novelist & Essayist",
    imageUrl: "",
    gradient: "from-emerald-400 to-cyan-600",
    emoji: "📖",
  },
  {
    text: "Another world is not only possible, she is on her way. On a quiet day, I can hear her breathing.",
    author: "Arundhati Roy",
    role: "Indian Novelist & Essayist",
    imageUrl: "",
    gradient: "from-teal-400 to-blue-600",
    emoji: "🌏",
  },
  {
    text: "To love. To be loved. To never forget your own insignificance.",
    author: "Arundhati Roy",
    role: "Indian Novelist & Essayist",
    imageUrl: "",
    gradient: "from-sky-400 to-indigo-600",
    emoji: "🌊",
  },

  // Jhumpa Lahiri (82-83)
  {
    text: "That's the thing about books. They let you travel without moving your feet.",
    author: "Jhumpa Lahiri",
    role: "Indian-American Novelist",
    imageUrl: "",
    gradient: "from-indigo-400 to-purple-600",
    emoji: "✈️",
  },
  {
    text: "You are still young, free. Do yourself a favor. Before it's too late, without thinking too much about it first, pack a pillow and a blanket and see as much of the world as you can.",
    author: "Jhumpa Lahiri",
    role: "Indian-American Novelist",
    imageUrl: "",
    gradient: "from-blue-400 to-violet-600",
    emoji: "🧳",
  },

  // Margaret Atwood (84-86)
  {
    text: "A word after a word after a word is power.",
    author: "Margaret Atwood",
    role: "Novelist & Poet",
    imageUrl: "",
    gradient: "from-red-400 to-amber-600",
    emoji: "🖋️",
  },
  {
    text: "In the spring, at the end of the day, you should smell like dirt.",
    author: "Margaret Atwood",
    role: "Novelist & Poet",
    imageUrl: "",
    gradient: "from-green-400 to-lime-600",
    emoji: "🌱",
  },
  {
    text: "War is what happens when language fails.",
    author: "Margaret Atwood",
    role: "Novelist & Poet",
    imageUrl: "",
    gradient: "from-gray-400 to-red-600",
    emoji: "📝",
  },

  // Chimamanda Ngozi Adichie (87-89)
  {
    text: "The single story creates stereotypes, and the problem with stereotypes is not that they are untrue, but that they are incomplete.",
    author: "Chimamanda Ngozi Adichie",
    role: "Novelist & Essayist",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "🌍",
  },
  {
    text: "We teach girls to shrink themselves, to make themselves smaller.",
    author: "Chimamanda Ngozi Adichie",
    role: "Novelist & Essayist",
    imageUrl: "",
    gradient: "from-purple-400 to-fuchsia-600",
    emoji: "👑",
  },
  {
    text: "Culture does not make people. People make culture.",
    author: "Chimamanda Ngozi Adichie",
    role: "Novelist & Essayist",
    imageUrl: "",
    gradient: "from-orange-400 to-yellow-600",
    emoji: "🏗️",
  },

  // Isabel Allende (90-91)
  {
    text: "Write what should not be forgotten.",
    author: "Isabel Allende",
    role: "Chilean Novelist",
    imageUrl: "",
    gradient: "from-rose-400 to-orange-600",
    emoji: "✍️",
  },
  {
    text: "The longer I live, the more uninformed I feel. Only the young have an explanation for everything.",
    author: "Isabel Allende",
    role: "Chilean Novelist",
    imageUrl: "",
    gradient: "from-amber-400 to-rose-600",
    emoji: "🌄",
  },

  // Gabriela Mistral (92-93)
  {
    text: "Many things we need can wait. The child cannot. Now is the time his bones are formed, his mind developed. To him, we cannot say tomorrow. His name is now.",
    author: "Gabriela Mistral",
    role: "Chilean Poet & Nobel Laureate",
    imageUrl: "",
    gradient: "from-sky-400 to-teal-600",
    emoji: "👶",
  },
  {
    text: "We are guilty of many errors and many faults, but our worst crime is abandoning the children.",
    author: "Gabriela Mistral",
    role: "Chilean Poet & Nobel Laureate",
    imageUrl: "",
    gradient: "from-blue-400 to-emerald-600",
    emoji: "🌻",
  },

  // Wislawa Szymborska (94-96)
  {
    text: "Whatever inspiration is, it's born from a continuous I don't know.",
    author: "Wislawa Szymborska",
    role: "Polish Poet & Nobel Laureate",
    imageUrl: "",
    gradient: "from-violet-400 to-indigo-600",
    emoji: "❓",
  },
  {
    text: "All the best have something in common, a regard for reality, an agreement to its primacy over the imagination.",
    author: "Wislawa Szymborska",
    role: "Polish Poet & Nobel Laureate",
    imageUrl: "",
    gradient: "from-indigo-400 to-sky-600",
    emoji: "🔮",
  },
  {
    text: "I prefer the absurdity of writing poems to the absurdity of not writing poems.",
    author: "Wislawa Szymborska",
    role: "Polish Poet & Nobel Laureate",
    imageUrl: "",
    gradient: "from-cyan-400 to-violet-600",
    emoji: "📝",
  },

  // Anna Akhmatova (97-100)
  {
    text: "I have learned to live simply, wisely, to look at the sky and pray to God.",
    author: "Anna Akhmatova",
    role: "Russian Poet",
    imageUrl: "",
    gradient: "from-blue-400 to-gray-600",
    emoji: "🙏",
  },
  {
    text: "I am in the middle of it: chaos and poetry; poetry and love and again, complete chaos. Pain, disorder, occasional clarity; ordinary day-to-day crap.",
    author: "Anna Akhmatova",
    role: "Russian Poet",
    imageUrl: "",
    gradient: "from-purple-400 to-slate-600",
    emoji: "🌪️",
  },
  {
    text: "But I warn you, I am living for the last time.",
    author: "Anna Akhmatova",
    role: "Russian Poet",
    imageUrl: "",
    gradient: "from-red-400 to-violet-600",
    emoji: "⚡",
  },
  {
    text: "The word landed with the weight of a stone on my still-living breast.",
    author: "Anna Akhmatova",
    role: "Russian Poet",
    imageUrl: "",
    gradient: "from-slate-400 to-indigo-600",
    emoji: "🪨",
  },
];
