import { Quote } from '../types';

export const scientistQuotes: Quote[] = [
  // --- Marie Curie (1-5) ---
  {
    text: "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.",
    author: "Marie Curie",
    role: "Nobel Prize-winning physicist & chemist",
    imageUrl: "",
    gradient: "from-indigo-400 to-indigo-600",
    emoji: "⚗️",
  },
  {
    text: "I am among those who think that science has great beauty.",
    author: "Marie Curie",
    role: "Nobel Prize-winning physicist & chemist",
    imageUrl: "",
    gradient: "from-purple-400 to-purple-600",
    emoji: "🔬",
  },
  {
    text: "Be less curious about people and more curious about ideas.",
    author: "Marie Curie",
    role: "Nobel Prize-winning physicist & chemist",
    imageUrl: "",
    gradient: "from-violet-400 to-violet-600",
    emoji: "💡",
  },
  {
    text: "One never notices what has been done; one can only see what remains to be done.",
    author: "Marie Curie",
    role: "Nobel Prize-winning physicist & chemist",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-fuchsia-600",
    emoji: "⚗️",
  },
  {
    text: "I was taught that the way of progress was neither swift nor easy.",
    author: "Marie Curie",
    role: "Nobel Prize-winning physicist & chemist",
    imageUrl: "",
    gradient: "from-blue-400 to-indigo-600",
    emoji: "🔬",
  },

  // --- Rosalind Franklin (6-8) ---
  {
    text: "Science and everyday life cannot and should not be separated.",
    author: "Rosalind Franklin",
    role: "Biophysicist & X-ray crystallographer",
    imageUrl: "",
    gradient: "from-teal-400 to-teal-600",
    emoji: "🧬",
  },
  {
    text: "In my view, all that is necessary for faith is the belief that by doing our best we shall succeed in our aims: the improvement of mankind.",
    author: "Rosalind Franklin",
    role: "Biophysicist & X-ray crystallographer",
    imageUrl: "",
    gradient: "from-cyan-400 to-cyan-600",
    emoji: "🧬",
  },
  {
    text: "You look at science (or at least talk of it) as some sort of demoralising invention of man, something apart from real life. But science and everyday life cannot and should not be separated.",
    author: "Rosalind Franklin",
    role: "Biophysicist & X-ray crystallographer",
    imageUrl: "",
    gradient: "from-emerald-400 to-teal-600",
    emoji: "🔬",
  },

  // --- Barbara McClintock (9-11) ---
  {
    text: "If you know you are on the right track, if you have this inner knowledge, then nobody can turn you off... no matter what they say.",
    author: "Barbara McClintock",
    role: "Nobel Prize-winning cytogeneticist",
    imageUrl: "",
    gradient: "from-green-400 to-green-600",
    emoji: "🧬",
  },
  {
    text: "I was just so interested in what I was doing I could hardly wait to get up in the morning and get at it.",
    author: "Barbara McClintock",
    role: "Nobel Prize-winning cytogeneticist",
    imageUrl: "",
    gradient: "from-lime-400 to-green-600",
    emoji: "🌱",
  },
  {
    text: "When you have that feeling, give it every confidence. That is a deep understanding.",
    author: "Barbara McClintock",
    role: "Nobel Prize-winning cytogeneticist",
    imageUrl: "",
    gradient: "from-emerald-400 to-emerald-600",
    emoji: "🔬",
  },

  // --- Ada Lovelace (12-15) ---
  {
    text: "That brain of mine is something more than merely mortal; as time will show.",
    author: "Ada Lovelace",
    role: "Pioneer of computer programming",
    imageUrl: "",
    gradient: "from-rose-400 to-rose-600",
    emoji: "💻",
  },
  {
    text: "The Analytical Engine weaves algebraical patterns just as the Jacquard loom weaves flowers and leaves.",
    author: "Ada Lovelace",
    role: "Pioneer of computer programming",
    imageUrl: "",
    gradient: "from-pink-400 to-pink-600",
    emoji: "💡",
  },
  {
    text: "I never am really satisfied that I understand anything; because, understand it well as I may, my comprehension can only be an infinitesimal fraction of all I want to understand.",
    author: "Ada Lovelace",
    role: "Pioneer of computer programming",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-pink-600",
    emoji: "💻",
  },
  {
    text: "The science of operations, as derived from mathematics more especially, is a science of itself, and has its own abstract truth and value.",
    author: "Ada Lovelace",
    role: "Pioneer of computer programming",
    imageUrl: "",
    gradient: "from-purple-400 to-pink-600",
    emoji: "🔢",
  },

  // --- Grace Hopper (16-20) ---
  {
    text: "The most dangerous phrase in the language is, 'We've always done it this way.'",
    author: "Grace Hopper",
    role: "Computer science pioneer & Navy Rear Admiral",
    imageUrl: "",
    gradient: "from-blue-400 to-blue-600",
    emoji: "💻",
  },
  {
    text: "A ship in port is safe, but that's not what ships are built for.",
    author: "Grace Hopper",
    role: "Computer science pioneer & Navy Rear Admiral",
    imageUrl: "",
    gradient: "from-sky-400 to-blue-600",
    emoji: "🚢",
  },
  {
    text: "If it's a good idea, go ahead and do it. It is much easier to apologize than it is to get permission.",
    author: "Grace Hopper",
    role: "Computer science pioneer & Navy Rear Admiral",
    imageUrl: "",
    gradient: "from-indigo-400 to-blue-600",
    emoji: "💡",
  },
  {
    text: "One accurate measurement is worth a thousand expert opinions.",
    author: "Grace Hopper",
    role: "Computer science pioneer & Navy Rear Admiral",
    imageUrl: "",
    gradient: "from-slate-400 to-blue-600",
    emoji: "🔬",
  },
  {
    text: "Humans are allergic to change. They love to say, 'We've always done it this way.' I try to fight that.",
    author: "Grace Hopper",
    role: "Computer science pioneer & Navy Rear Admiral",
    imageUrl: "",
    gradient: "from-cyan-400 to-blue-600",
    emoji: "💻",
  },

  // --- Katherine Johnson (21-24) ---
  {
    text: "I counted everything. I counted the steps to the road, the steps up to church, the number of dishes and silverware I washed.",
    author: "Katherine Johnson",
    role: "NASA mathematician",
    imageUrl: "",
    gradient: "from-amber-400 to-amber-600",
    emoji: "🚀",
  },
  {
    text: "Girls are capable of doing everything men are capable of doing. Sometimes they have more imagination than men.",
    author: "Katherine Johnson",
    role: "NASA mathematician",
    imageUrl: "",
    gradient: "from-yellow-400 to-amber-600",
    emoji: "🔢",
  },
  {
    text: "I felt most at ease working with the research mathematicians. They were glad to have me.",
    author: "Katherine Johnson",
    role: "NASA mathematician",
    imageUrl: "",
    gradient: "from-orange-400 to-amber-600",
    emoji: "🚀",
  },
  {
    text: "Like what you do, and then you will do your best.",
    author: "Katherine Johnson",
    role: "NASA mathematician",
    imageUrl: "",
    gradient: "from-amber-400 to-orange-600",
    emoji: "💡",
  },

  // --- Jane Goodall (25-29) ---
  {
    text: "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    author: "Jane Goodall",
    role: "Primatologist & anthropologist",
    imageUrl: "",
    gradient: "from-green-400 to-emerald-600",
    emoji: "🌿",
  },
  {
    text: "The greatest danger to our future is apathy.",
    author: "Jane Goodall",
    role: "Primatologist & anthropologist",
    imageUrl: "",
    gradient: "from-lime-400 to-emerald-600",
    emoji: "🌍",
  },
  {
    text: "Only if we understand, can we care. Only if we care, will we help. Only if we help, shall all be saved.",
    author: "Jane Goodall",
    role: "Primatologist & anthropologist",
    imageUrl: "",
    gradient: "from-teal-400 to-green-600",
    emoji: "🌿",
  },
  {
    text: "Every individual matters. Every individual has a role to play. Every individual makes a difference.",
    author: "Jane Goodall",
    role: "Primatologist & anthropologist",
    imageUrl: "",
    gradient: "from-emerald-400 to-green-600",
    emoji: "🌱",
  },
  {
    text: "You cannot get through a single day without having an impact on the world around you.",
    author: "Jane Goodall",
    role: "Primatologist & anthropologist",
    imageUrl: "",
    gradient: "from-green-400 to-lime-600",
    emoji: "🌍",
  },

  // --- Rachel Carson (30-32) ---
  {
    text: "The more clearly we can focus our attention on the wonders and realities of the universe about us, the less taste we shall have for destruction.",
    author: "Rachel Carson",
    role: "Marine biologist & conservationist",
    imageUrl: "",
    gradient: "from-sky-400 to-teal-600",
    emoji: "🌊",
  },
  {
    text: "In every outward and visible grace of life, in every fair and noble quality of our nature, we are indebted to the sea.",
    author: "Rachel Carson",
    role: "Marine biologist & conservationist",
    imageUrl: "",
    gradient: "from-blue-400 to-teal-600",
    emoji: "🌊",
  },
  {
    text: "Those who contemplate the beauty of the earth find reserves of strength that will endure as long as life lasts.",
    author: "Rachel Carson",
    role: "Marine biologist & conservationist",
    imageUrl: "",
    gradient: "from-cyan-400 to-teal-600",
    emoji: "🌿",
  },

  // --- Sylvia Earle (33-35) ---
  {
    text: "No water, no life. No blue, no green.",
    author: "Sylvia Earle",
    role: "Marine biologist & oceanographer",
    imageUrl: "",
    gradient: "from-blue-400 to-cyan-600",
    emoji: "🌊",
  },
  {
    text: "The best scientists and explorers have the attributes of kids! They ask questions and have a sense of wonder.",
    author: "Sylvia Earle",
    role: "Marine biologist & oceanographer",
    imageUrl: "",
    gradient: "from-sky-400 to-cyan-600",
    emoji: "🔭",
  },
  {
    text: "I have lots of heroes: anyone and everyone who does whatever they can to leave the natural world better than they found it.",
    author: "Sylvia Earle",
    role: "Marine biologist & oceanographer",
    imageUrl: "",
    gradient: "from-teal-400 to-cyan-600",
    emoji: "🌊",
  },

  // --- Hedy Lamarr (36-38) ---
  {
    text: "All creative people want to do the unexpected.",
    author: "Hedy Lamarr",
    role: "Actress & inventor of frequency hopping",
    imageUrl: "",
    gradient: "from-rose-400 to-purple-600",
    emoji: "📡",
  },
  {
    text: "Hope and curiosity about the future seemed better than guarantees. That's the best I can do.",
    author: "Hedy Lamarr",
    role: "Actress & inventor of frequency hopping",
    imageUrl: "",
    gradient: "from-pink-400 to-purple-600",
    emoji: "💡",
  },
  {
    text: "Improving things is central to my nature.",
    author: "Hedy Lamarr",
    role: "Actress & inventor of frequency hopping",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-purple-600",
    emoji: "📡",
  },

  // --- Chien-Shiung Wu (39-41) ---
  {
    text: "There is only one thing worse than coming home from the lab to a sink full of dirty dishes, and that is not going to the lab at all.",
    author: "Chien-Shiung Wu",
    role: "Experimental physicist, the First Lady of Physics",
    imageUrl: "",
    gradient: "from-red-400 to-red-600",
    emoji: "⚛️",
  },
  {
    text: "It is shameful that there are so few women in science. In China there are many women in physics. There is no reason why this should not be so.",
    author: "Chien-Shiung Wu",
    role: "Experimental physicist, the First Lady of Physics",
    imageUrl: "",
    gradient: "from-orange-400 to-red-600",
    emoji: "🔬",
  },
  {
    text: "I wonder whether the tiny atoms and nuclei, or the mathematical symbols, or the DNA molecules have any preference for either masculine or feminine treatment.",
    author: "Chien-Shiung Wu",
    role: "Experimental physicist, the First Lady of Physics",
    imageUrl: "",
    gradient: "from-rose-400 to-red-600",
    emoji: "⚛️",
  },

  // --- Mae Jemison (42-45) ---
  {
    text: "Never be limited by other people's limited imaginations.",
    author: "Mae Jemison",
    role: "First African-American woman in space",
    imageUrl: "",
    gradient: "from-violet-400 to-indigo-600",
    emoji: "🚀",
  },
  {
    text: "Don't let anyone rob you of your imagination, your creativity, or your curiosity.",
    author: "Mae Jemison",
    role: "First African-American woman in space",
    imageUrl: "",
    gradient: "from-purple-400 to-indigo-600",
    emoji: "🚀",
  },
  {
    text: "The difference between science and the arts is not that they are different sides of the same coin... but that they are manifestations of the same thing.",
    author: "Mae Jemison",
    role: "First African-American woman in space",
    imageUrl: "",
    gradient: "from-indigo-400 to-violet-600",
    emoji: "🔭",
  },
  {
    text: "I always knew I'd go to space.",
    author: "Mae Jemison",
    role: "First African-American woman in space",
    imageUrl: "",
    gradient: "from-blue-400 to-violet-600",
    emoji: "🚀",
  },

  // --- Sally Ride (46-49) ---
  {
    text: "I would like to be remembered as someone who was not afraid to do what she wanted to do, and as someone who took risks along the way in order to achieve her goals.",
    author: "Sally Ride",
    role: "First American woman in space",
    imageUrl: "",
    gradient: "from-sky-400 to-indigo-600",
    emoji: "🚀",
  },
  {
    text: "Young girls need to see role models in whatever careers they may choose, just so they can picture themselves doing those jobs someday.",
    author: "Sally Ride",
    role: "First American woman in space",
    imageUrl: "",
    gradient: "from-blue-400 to-sky-600",
    emoji: "🔭",
  },
  {
    text: "Studying whether there's life on Mars or studying how the universe began, there's something magical about pushing back the frontiers of knowledge.",
    author: "Sally Ride",
    role: "First American woman in space",
    imageUrl: "",
    gradient: "from-indigo-400 to-sky-600",
    emoji: "🚀",
  },
  {
    text: "The stars don't look bigger, but they do look brighter.",
    author: "Sally Ride",
    role: "First American woman in space",
    imageUrl: "",
    gradient: "from-slate-400 to-indigo-600",
    emoji: "✨",
  },

  // --- Valentina Tereshkova (50-52) ---
  {
    text: "Once you've been in space, you appreciate how small and fragile the Earth is.",
    author: "Valentina Tereshkova",
    role: "First woman in space",
    imageUrl: "",
    gradient: "from-red-400 to-orange-600",
    emoji: "🚀",
  },
  {
    text: "If women can be railroad workers in Russia, why can't they fly in space?",
    author: "Valentina Tereshkova",
    role: "First woman in space",
    imageUrl: "",
    gradient: "from-orange-400 to-yellow-600",
    emoji: "🌍",
  },
  {
    text: "Hey sky, take off your hat, I'm on my way!",
    author: "Valentina Tereshkova",
    role: "First woman in space",
    imageUrl: "",
    gradient: "from-amber-400 to-red-600",
    emoji: "🚀",
  },

  // --- Maryam Mirzakhani (53-55) ---
  {
    text: "The beauty of mathematics only shows itself to more patient followers.",
    author: "Maryam Mirzakhani",
    role: "First woman to win the Fields Medal",
    imageUrl: "",
    gradient: "from-teal-400 to-emerald-600",
    emoji: "🔢",
  },
  {
    text: "I don't think that everyone should become a mathematician, but I do believe that many students don't give mathematics a real chance.",
    author: "Maryam Mirzakhani",
    role: "First woman to win the Fields Medal",
    imageUrl: "",
    gradient: "from-emerald-400 to-teal-600",
    emoji: "💡",
  },
  {
    text: "You have to spend some energy and effort to see the beauty of math.",
    author: "Maryam Mirzakhani",
    role: "First woman to win the Fields Medal",
    imageUrl: "",
    gradient: "from-cyan-400 to-emerald-600",
    emoji: "🔢",
  },

  // --- Emmy Noether (56-58) ---
  {
    text: "My methods are really methods of working and thinking; this is why they have crept in everywhere anonymously.",
    author: "Emmy Noether",
    role: "Groundbreaking mathematician & algebraist",
    imageUrl: "",
    gradient: "from-purple-400 to-fuchsia-600",
    emoji: "🔢",
  },
  {
    text: "If one proves the equality of two numbers a and b by showing first that a is less than or equal to b and then that b is less than or equal to a, it is unfair; one should instead show that they are really equal by disclosing the inner ground for their equality.",
    author: "Emmy Noether",
    role: "Groundbreaking mathematician & algebraist",
    imageUrl: "",
    gradient: "from-violet-400 to-fuchsia-600",
    emoji: "💡",
  },
  {
    text: "I am not, however, for the moment, able to pursue a discussion of algebraic number fields.",
    author: "Emmy Noether",
    role: "Groundbreaking mathematician & algebraist",
    imageUrl: "",
    gradient: "from-fuchsia-400 to-violet-600",
    emoji: "🔢",
  },

  // --- Dian Fossey (59-61) ---
  {
    text: "The man who kills the animals today is the man who kills the people who get in his way tomorrow.",
    author: "Dian Fossey",
    role: "Primatologist & gorilla conservationist",
    imageUrl: "",
    gradient: "from-green-400 to-teal-600",
    emoji: "🦍",
  },
  {
    text: "When you realize the value of all life, you dwell less on what is past and concentrate more on the preservation of the future.",
    author: "Dian Fossey",
    role: "Primatologist & gorilla conservationist",
    imageUrl: "",
    gradient: "from-emerald-400 to-lime-600",
    emoji: "🌿",
  },
  {
    text: "I feel more comfortable with gorillas than people. I can anticipate what a gorilla's going to do, and they're purely motivated.",
    author: "Dian Fossey",
    role: "Primatologist & gorilla conservationist",
    imageUrl: "",
    gradient: "from-lime-400 to-teal-600",
    emoji: "🦍",
  },

  // --- Wangari Maathai (62-63) ---
  {
    text: "We cannot tire or give up. We owe it to the present and future generations of all species to rise up and walk!",
    author: "Wangari Maathai",
    role: "Nobel Peace Prize-winning environmentalist",
    imageUrl: "",
    gradient: "from-teal-400 to-lime-600",
    emoji: "🌱",
  },
  {
    text: "We owe it to ourselves and to the next generation to conserve the environment so that we can bequeath our children a sustainable world.",
    author: "Wangari Maathai",
    role: "Nobel Peace Prize-winning environmentalist",
    imageUrl: "",
    gradient: "from-green-400 to-yellow-600",
    emoji: "🌳",
  },

  // --- Tu Youyou (66-68) ---
  {
    text: "Every scientist dreams of doing something that can help the world.",
    author: "Tu Youyou",
    role: "Nobel Prize-winning pharmaceutical chemist",
    imageUrl: "",
    gradient: "from-red-400 to-rose-600",
    emoji: "⚗️",
  },
  {
    text: "I felt a great responsibility — so many people were dying from malaria, I had to find a cure.",
    author: "Tu Youyou",
    role: "Nobel Prize-winning pharmaceutical chemist",
    imageUrl: "",
    gradient: "from-rose-400 to-pink-600",
    emoji: "🔬",
  },
  {
    text: "The discovery of artemisinin is a gift from traditional Chinese medicine to the world.",
    author: "Tu Youyou",
    role: "Nobel Prize-winning pharmaceutical chemist",
    imageUrl: "",
    gradient: "from-pink-400 to-rose-600",
    emoji: "⚗️",
  },

  // --- Jennifer Doudna (69-72) ---
  {
    text: "The power to control our species' genetic future is awesome and terrifying. Deciding how to handle it may be the biggest challenge we have ever faced.",
    author: "Jennifer Doudna",
    role: "Nobel Prize-winning biochemist, CRISPR co-developer",
    imageUrl: "",
    gradient: "from-blue-400 to-purple-600",
    emoji: "🧬",
  },
  {
    text: "CRISPR isn't good or evil — it's a tool. We have a responsibility to use it wisely.",
    author: "Jennifer Doudna",
    role: "Nobel Prize-winning biochemist, CRISPR co-developer",
    imageUrl: "",
    gradient: "from-indigo-400 to-purple-600",
    emoji: "🧬",
  },
  {
    text: "I think the most important thing is to have curiosity. Follow your curiosity. Let it lead you.",
    author: "Jennifer Doudna",
    role: "Nobel Prize-winning biochemist, CRISPR co-developer",
    imageUrl: "",
    gradient: "from-violet-400 to-blue-600",
    emoji: "🔬",
  },
  {
    text: "The real challenge is to figure out how to apply CRISPR in a way that brings the most benefit.",
    author: "Jennifer Doudna",
    role: "Nobel Prize-winning biochemist, CRISPR co-developer",
    imageUrl: "",
    gradient: "from-purple-400 to-blue-600",
    emoji: "🧬",
  },

  // --- Reshma Saujani ---
  {
    text: "Bravery, not perfection. That's what we need to teach our girls.",
    author: "Reshma Saujani",
    role: "Founder of Girls Who Code",
    imageUrl: "",
    gradient: "from-rose-400 to-orange-600",
    emoji: "💡",
  },
  {
    text: "We're raising our girls to be perfect, and we're raising our boys to be brave.",
    author: "Reshma Saujani",
    role: "Founder of Girls Who Code",
    imageUrl: "",
    gradient: "from-red-400 to-pink-600",
    emoji: "💻",
  },

  // --- Kalpana Chawla (80-83) ---
  {
    text: "The path from dreams to success does exist. May you have the vision to find it, the courage to get on to it, and the perseverance to follow it.",
    author: "Kalpana Chawla",
    role: "First Indian-American woman in space",
    imageUrl: "",
    gradient: "from-orange-400 to-amber-600",
    emoji: "🚀",
  },
  {
    text: "Do something you love. When you love what you do, your passions and enthusiasm make you push forward and do better.",
    author: "Kalpana Chawla",
    role: "First Indian-American woman in space",
    imageUrl: "",
    gradient: "from-amber-400 to-yellow-600",
    emoji: "✨",
  },
  {
    text: "When you look at the stars and the galaxy, you feel that you are not just from any particular piece of land, but from the solar system.",
    author: "Kalpana Chawla",
    role: "First Indian-American woman in space",
    imageUrl: "",
    gradient: "from-yellow-400 to-orange-600",
    emoji: "🔭",
  },
  {
    text: "You are just your intelligence.",
    author: "Kalpana Chawla",
    role: "First Indian-American woman in space",
    imageUrl: "",
    gradient: "from-orange-400 to-red-600",
    emoji: "🚀",
  },

  // --- Sunita Williams (84-86) ---
  {
    text: "If you really want something in this world, you have to work for it. Dreams don't come true just by dreaming.",
    author: "Sunita Williams",
    role: "NASA astronaut of Indian descent",
    imageUrl: "",
    gradient: "from-sky-400 to-violet-600",
    emoji: "🚀",
  },
  {
    text: "Don't limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you.",
    author: "Sunita Williams",
    role: "NASA astronaut of Indian descent",
    imageUrl: "",
    gradient: "from-blue-400 to-violet-600",
    emoji: "🔭",
  },
  {
    text: "Being in space taught me so much about our world. It's very beautiful, fragile, and needs to be protected.",
    author: "Sunita Williams",
    role: "NASA astronaut of Indian descent",
    imageUrl: "",
    gradient: "from-indigo-400 to-violet-600",
    emoji: "🌍",
  },

  // --- Tessy Thomas (87-89) ---
  {
    text: "It does not matter whether you are a man or a woman. What matters is whether you can deliver.",
    author: "Tessy Thomas",
    role: "India's Missile Woman, Agni-V project director",
    imageUrl: "",
    gradient: "from-orange-400 to-rose-600",
    emoji: "🚀",
  },
  {
    text: "I want young girls to know that they can achieve anything they set their minds to. There are no limits.",
    author: "Tessy Thomas",
    role: "India's Missile Woman, Agni-V project director",
    imageUrl: "",
    gradient: "from-red-400 to-amber-600",
    emoji: "💡",
  },
  {
    text: "For me, the success of Agni-V was a dream fulfilled. It was the culmination of years of dedicated teamwork.",
    author: "Tessy Thomas",
    role: "India's Missile Woman, Agni-V project director",
    imageUrl: "",
    gradient: "from-amber-400 to-rose-600",
    emoji: "🚀",
  },

  // --- Ritu Karidhal (90-92) ---
  {
    text: "Failure is a stepping stone to success. Each failure taught us something that brought us closer to Mars.",
    author: "Ritu Karidhal",
    role: "ISRO scientist, Mars Orbiter Mission deputy operations director",
    imageUrl: "",
    gradient: "from-red-400 to-orange-600",
    emoji: "🚀",
  },
  {
    text: "If we can dream it, we can do it. That was the spirit of the Mars mission.",
    author: "Ritu Karidhal",
    role: "ISRO scientist, Mars Orbiter Mission deputy operations director",
    imageUrl: "",
    gradient: "from-orange-400 to-pink-600",
    emoji: "🔭",
  },
  {
    text: "Space is not just for a few countries or a few people. It is for all of humanity.",
    author: "Ritu Karidhal",
    role: "ISRO scientist, Mars Orbiter Mission deputy operations director",
    imageUrl: "",
    gradient: "from-rose-400 to-amber-600",
    emoji: "🌍",
  },

  // --- Additional quotes to reach 100 (93-100) ---
  {
    text: "Life is not easy for any of us. But what of that? We must have perseverance and above all confidence in ourselves.",
    author: "Marie Curie",
    role: "Nobel Prize-winning physicist & chemist",
    imageUrl: "",
    gradient: "from-indigo-400 to-fuchsia-600",
    emoji: "⚗️",
  },
  {
    text: "I see no reason why I should be first. I just did what I had to do.",
    author: "Valentina Tereshkova",
    role: "First woman in space",
    imageUrl: "",
    gradient: "from-red-400 to-yellow-600",
    emoji: "🚀",
  },
  {
    text: "I think it's very important for little girls growing up, and young women, to have one in every walk of life. So from time to time I'm happy to be that person.",
    author: "Mae Jemison",
    role: "First African-American woman in space",
    imageUrl: "",
    gradient: "from-purple-400 to-violet-600",
    emoji: "🚀",
  },
  {
    text: "I was raised to believe that excellence is the best deterrent to racism or sexism. And that's how I operate my life.",
    author: "Mae Jemison",
    role: "First African-American woman in space",
    imageUrl: "",
    gradient: "from-indigo-400 to-fuchsia-600",
    emoji: "✨",
  },
  {
    text: "I think the key is for women not to set any limits.",
    author: "Martina Navratilova",
    role: "Champion athlete & women's rights advocate",
    imageUrl: "",
    gradient: "from-teal-400 to-blue-600",
    emoji: "💡",
  },
];
