import { Task, Quote } from './types';

export const initialTasks: Task[] = [
  {
    id: '1',
    owner: 'Reema',
    action: 'Meet Linda today: understand current segmentation, contact lists, newsletter workflows.',
    deadline: '9 Apr',
    deadlineDate: new Date(2026, 3, 9),
    status: 'In progress',
    subtasks: [
      { id: '1-1', title: 'Review current segmentation model', hoursRequired: 2, completed: true },
      { id: '1-2', title: 'Map contact list sources', hoursRequired: 1.5, completed: false },
      { id: '1-3', title: 'Document newsletter workflow', hoursRequired: 1, completed: false },
    ],
  },
  {
    id: '2',
    owner: 'Reema',
    action: 'Get CRM (C4/HANA) walkthrough from Jan – understand existing data structure before designing Marketing Cloud segments.',
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'New',
    subtasks: [
      { id: '2-1', title: 'Schedule walkthrough with Jan', hoursRequired: 0.5, completed: false },
      { id: '2-2', title: 'Document data fields & relationships', hoursRequired: 3, completed: false },
      { id: '2-3', title: 'Map CRM fields to Marketing Cloud', hoursRequired: 2, completed: false },
    ],
  },
  {
    id: '3',
    owner: 'Reema',
    action: 'Produce "what is currently possible" Marketing Cloud capability document after Linda meeting.',
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'New',
    subtasks: [
      { id: '3-1', title: 'Audit current Marketing Cloud features', hoursRequired: 2, completed: false },
      { id: '3-2', title: 'Draft capability document', hoursRequired: 3, completed: false },
      { id: '3-3', title: 'Review with stakeholders', hoursRequired: 1, completed: false },
    ],
  },
  {
    id: '4',
    owner: 'Reema',
    action: 'Draft Marketing Cloud segmentation architecture proposal (customer groups, countries, roles, nomenclature). Share with Jacek before kickoff.',
    deadline: 'w/c 21 Apr',
    deadlineDate: new Date(2026, 3, 21),
    status: 'New',
    subtasks: [
      { id: '4-1', title: 'Define customer group taxonomy', hoursRequired: 2, completed: false },
      { id: '4-2', title: 'Create country/role matrix', hoursRequired: 2, completed: false },
      { id: '4-3', title: 'Draft naming conventions', hoursRequired: 1, completed: false },
      { id: '4-4', title: 'Write architecture proposal', hoursRequired: 3, completed: false },
    ],
  },
  {
    id: '5',
    owner: 'Reema',
    action: 'Arrange Prodware call (with Jan + Thomas) to clarify: social connector, Query Assist, licence count, integration with CRM.',
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'Carried fwd',
    subtasks: [
      { id: '5-1', title: 'Prepare agenda and questions', hoursRequired: 1, completed: true },
      { id: '5-2', title: 'Schedule call with all parties', hoursRequired: 0.5, completed: false },
      { id: '5-3', title: 'Document findings', hoursRequired: 1.5, completed: false },
    ],
  },
  {
    id: '6',
    owner: 'Reema',
    action: 'Draft Marketing Cloud MVP proposal + target-state document.',
    deadline: 'w/c 21 Apr',
    deadlineDate: new Date(2026, 3, 21),
    status: 'Carried fwd',
    subtasks: [
      { id: '6-1', title: 'Define MVP scope', hoursRequired: 2, completed: false },
      { id: '6-2', title: 'Create target-state vision', hoursRequired: 3, completed: false },
      { id: '6-3', title: 'Write proposal document', hoursRequired: 4, completed: false },
    ],
  },
  {
    id: '7',
    owner: 'Reema',
    action: 'Identify 2-3 Indian rendering agencies (STEP-to-render) with international/German brand credentials.',
    deadline: 'Mid-Apr',
    deadlineDate: new Date(2026, 3, 15),
    status: 'Carried fwd',
    subtasks: [
      { id: '7-1', title: 'Research agencies with German brand work', hoursRequired: 3, completed: false },
      { id: '7-2', title: 'Review portfolios and pricing', hoursRequired: 2, completed: false },
      { id: '7-3', title: 'Create shortlist with recommendations', hoursRequired: 1, completed: false },
    ],
  },
  {
    id: '8',
    owner: 'Reema',
    action: "Review Gosia's HWST drive; identify specific digital support areas (landing page, social).",
    deadline: 'w/c 8 Apr',
    deadlineDate: new Date(2026, 3, 8),
    status: 'Carried fwd',
    subtasks: [
      { id: '8-1', title: 'Review all HWST drive materials', hoursRequired: 2, completed: false },
      { id: '8-2', title: 'Identify digital gaps', hoursRequired: 1.5, completed: false },
      { id: '8-3', title: 'Propose support plan', hoursRequired: 1, completed: false },
    ],
  },
  {
    id: '9',
    owner: 'Reema',
    action: 'Verify DeepL English translations of Storatherm HF 500/800 promo materials with Gosia + Linda.',
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'New',
    subtasks: [
      { id: '9-1', title: 'Run DeepL translations', hoursRequired: 1, completed: false },
      { id: '9-2', title: 'Review with Gosia', hoursRequired: 1, completed: false },
      { id: '9-3', title: 'Final review with Linda', hoursRequired: 0.5, completed: false },
    ],
  },
  {
    id: '10',
    owner: 'Reema',
    action: "Draft strategic content playbook (beyond Linda's operational plan).",
    deadline: 'Before 20 Apr',
    deadlineDate: new Date(2026, 3, 20),
    status: 'New',
    subtasks: [
      { id: '10-1', title: 'Define content pillars', hoursRequired: 2, completed: false },
      { id: '10-2', title: 'Create channel strategy', hoursRequired: 2, completed: false },
      { id: '10-3', title: 'Draft playbook document', hoursRequired: 4, completed: false },
    ],
  },
  {
    id: '11',
    owner: 'Reema',
    action: "Get own Social Hub access (currently sharing Maik's). Analyse existing content/calendar.",
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'New',
    subtasks: [
      { id: '11-1', title: 'Request Social Hub access', hoursRequired: 0.5, completed: false },
      { id: '11-2', title: 'Audit existing content calendar', hoursRequired: 2, completed: false },
    ],
  },
  {
    id: '12',
    owner: 'Reema',
    action: 'Study Schneider Electric data-centre cooling pages as benchmark.',
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'New',
    subtasks: [
      { id: '12-1', title: 'Analyse Schneider page structure', hoursRequired: 1.5, completed: false },
      { id: '12-2', title: 'Document best practices', hoursRequired: 1, completed: false },
    ],
  },
  {
    id: '13',
    owner: 'Reema',
    action: 'Rewrite Switzerland/Michele LinkedIn post – remove IMI name.',
    deadline: '8 Apr',
    deadlineDate: new Date(2026, 3, 8),
    status: 'Due',
    subtasks: [
      { id: '13-1', title: 'Rewrite LinkedIn post copy', hoursRequired: 1, completed: false },
      { id: '13-2', title: 'Get approval and publish', hoursRequired: 0.5, completed: false },
    ],
  },
  {
    id: '14',
    owner: 'Jacek',
    action: 'Define Content Engine project scope + team; organise kickoff in April.',
    deadline: 'w/c 21 Apr',
    deadlineDate: new Date(2026, 3, 21),
    status: 'New',
    subtasks: [
      { id: '14-1', title: 'Define project scope document', hoursRequired: 3, completed: false },
      { id: '14-2', title: 'Identify team members', hoursRequired: 1, completed: false },
      { id: '14-3', title: 'Schedule kickoff meeting', hoursRequired: 0.5, completed: false },
    ],
  },
  {
    id: '15',
    owner: 'Jacek',
    action: 'Request Andreas to organise 4-5 product training sessions for Reema (online, April).',
    deadline: 'w/c 8 Apr',
    deadlineDate: new Date(2026, 3, 8),
    status: 'Carried fwd',
    subtasks: [
      { id: '15-1', title: 'Contact Andreas', hoursRequired: 0.5, completed: false },
      { id: '15-2', title: 'Define training topics', hoursRequired: 1, completed: false },
    ],
  },
  {
    id: '16',
    owner: 'Jacek',
    action: 'Share Schneider Electric data-centre link with Reema (done in-chat).',
    deadline: '9 Apr',
    deadlineDate: new Date(2026, 3, 9),
    status: 'Done',
    subtasks: [
      { id: '16-1', title: 'Share link', hoursRequired: 0.1, completed: true },
    ],
  },
  {
    id: '17',
    owner: 'Jacek',
    action: 'Re-establish expired recurring team meeting (Viktor, Linda, Reema).',
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'New',
    subtasks: [
      { id: '17-1', title: 'Find available time slot', hoursRequired: 0.5, completed: false },
      { id: '17-2', title: 'Send calendar invite', hoursRequired: 0.25, completed: false },
    ],
  },
  {
    id: '18',
    owner: 'Jacek',
    action: 'Schedule 20 April content/social strategy meeting: Jacek + Reema + Linda + David.',
    deadline: '9 Apr',
    deadlineDate: new Date(2026, 3, 9),
    status: 'Done',
    subtasks: [
      { id: '18-1', title: 'Send meeting invite', hoursRequired: 0.25, completed: true },
    ],
  },
  {
    id: '19',
    owner: 'Jacek',
    action: 'Confirm Karolina as budget-file contact for Reema.',
    deadline: 'w/c 8 Apr',
    deadlineDate: new Date(2026, 3, 8),
    status: 'Carried fwd',
    subtasks: [
      { id: '19-1', title: 'Confirm with Karolina', hoursRequired: 0.25, completed: false },
    ],
  },
  {
    id: '20',
    owner: 'J + R + Gosia',
    action: 'Three-way alignment: map project responsibilities, agree contribution model.',
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'Carried fwd',
    subtasks: [
      { id: '20-1', title: 'Prepare responsibility matrix', hoursRequired: 2, completed: false },
      { id: '20-2', title: 'Schedule alignment meeting', hoursRequired: 0.5, completed: false },
      { id: '20-3', title: 'Document agreed model', hoursRequired: 1, completed: false },
    ],
  },
  {
    id: '21',
    owner: 'Team',
    action: 'Content/Social Strategy meeting: social channels, Instagram consolidation, integration with Marketing Cloud.',
    deadline: '20 Apr',
    deadlineDate: new Date(2026, 3, 20),
    status: 'Scheduled',
    subtasks: [
      { id: '21-1', title: 'Prepare meeting agenda', hoursRequired: 1, completed: false },
      { id: '21-2', title: 'Compile channel audit data', hoursRequired: 2, completed: false },
      { id: '21-3', title: 'Prepare Instagram consolidation proposal', hoursRequired: 2, completed: false },
    ],
  },
  {
    id: '22',
    owner: 'Team',
    action: 'Dubai/Moustapha meeting: postponed (work-permit).',
    deadline: 'TBD',
    deadlineDate: null,
    status: 'On hold',
    subtasks: [],
  },
];

export const quotes: Quote[] = [
  {
    text: "The most difficult thing is the decision to act, the rest is merely tenacity.",
    author: "Amelia Earhart",
    role: "Aviation Pioneer",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Amelia_Earhart_standing_under_nose_of_her_Lockheed_Model_10-E_Electra%2C_small.jpg/220px-Amelia_Earhart_standing_under_nose_of_her_Lockheed_Model_10-E_Electra%2C_small.jpg",
    gradient: "from-amber-400 to-orange-500",
    emoji: "\u2708\uFE0F",
  },
  {
    text: "I am no bird; and no net ensnares me: I am a free human being with an independent will.",
    author: "Charlotte Bronte",
    role: "Poet & Novelist",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Charlotte_Bront%C3%AB.jpg/220px-Charlotte_Bront%C3%AB.jpg",
    gradient: "from-violet-400 to-purple-600",
    emoji: "\u270D\uFE0F",
  },
  {
    text: "It took me quite a long time to develop a voice, and now that I have it, I am not going to be silent.",
    author: "Madeleine Albright",
    role: "First Female US Secretary of State",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Albrightclinton.jpg/220px-Albrightclinton.jpg",
    gradient: "from-blue-400 to-indigo-600",
    emoji: "\u{1F5E3}\uFE0F",
  },
  {
    text: "I have learned over the years that when one's mind is made up, this diminishes fear.",
    author: "Rosa Parks",
    role: "Civil Rights Activist",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Rosaparks.jpg/220px-Rosaparks.jpg",
    gradient: "from-rose-400 to-red-600",
    emoji: "\u{1F4AA}",
  },
  {
    text: "You must do the things you think you cannot do.",
    author: "Eleanor Roosevelt",
    role: "Former First Lady & Activist",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Eleanor_Roosevelt_portrait_1933.jpg/220px-Eleanor_Roosevelt_portrait_1933.jpg",
    gradient: "from-teal-400 to-emerald-600",
    emoji: "\u{1F31F}",
  },
  {
    text: "I raise up my voice \u2014 not so that I can shout, but so that those without a voice can be heard.",
    author: "Malala Yousafzai",
    role: "Nobel Peace Laureate",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Malala_Yousafzai_at_Girl_Summit_2014-cropped.jpg/220px-Malala_Yousafzai_at_Girl_Summit_2014-cropped.jpg",
    gradient: "from-pink-400 to-rose-600",
    emoji: "\u{1F3C6}",
  },
  {
    text: "The question isn\u2019t who is going to let me; it\u2019s who is going to stop me.",
    author: "Ayn Rand",
    role: "Philosopher & Author",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Ayn_Rand_%281943_Talbot_portrait%29.jpg/220px-Ayn_Rand_%281943_Talbot_portrait%29.jpg",
    gradient: "from-slate-400 to-gray-700",
    emoji: "\u{1F4D6}",
  },
  {
    text: "I never dreamed about success. I worked for it.",
    author: "Estee Lauder",
    role: "Business Pioneer",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Est%C3%A9e_Lauder_by_Horst_P._Horst_%28cropped%29.jpg/220px-Est%C3%A9e_Lauder_by_Horst_P._Horst_%28cropped%29.jpg",
    gradient: "from-amber-300 to-yellow-600",
    emoji: "\u{1F48E}",
  },
  {
    text: "Champions keep playing until they get it right.",
    author: "Billie Jean King",
    role: "Tennis Champion & Equality Advocate",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Billie_Jean_King_2016.jpg/220px-Billie_Jean_King_2016.jpg",
    gradient: "from-green-400 to-emerald-600",
    emoji: "\u{1F3BE}",
  },
  {
    text: "The only way to do great work is to love what you do. If you haven\u2019t found it yet, keep looking.",
    author: "Serena Williams",
    role: "23-Time Grand Slam Champion",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Serena_Williams_at_2013_US_Open.jpg/220px-Serena_Williams_at_2013_US_Open.jpg",
    gradient: "from-fuchsia-500 to-purple-700",
    emoji: "\u{1F3BE}",
  },
  {
    text: "I\u2019ve failed over and over and over again in my life. And that is why I succeed.",
    author: "Mia Hamm",
    role: "Soccer Legend & Olympic Gold Medalist",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Mia_Hamm_toward_the_end_of_her_career.jpg/220px-Mia_Hamm_toward_the_end_of_her_career.jpg",
    gradient: "from-sky-400 to-blue-600",
    emoji: "\u26BD",
  },
  {
    text: "If you can see it, you can be it. Stop putting limitations on yourself.",
    author: "Simone Biles",
    role: "Most Decorated Gymnast in History",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Simone_Biles_in_2024_%28cropped%29.jpg/220px-Simone_Biles_in_2024_%28cropped%29.jpg",
    gradient: "from-red-400 to-pink-600",
    emoji: "\u{1F938}\u200D\u2640\uFE0F",
  },
  {
    text: "I do not wish women to have power over men; but over themselves.",
    author: "Mary Shelley",
    role: "Author of Frankenstein",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Mary_Wollstonecraft_Shelley_Rothwell.tif/lossy-page1-220px-Mary_Wollstonecraft_Shelley_Rothwell.tif.jpg",
    gradient: "from-indigo-400 to-violet-700",
    emoji: "\u{1F4DA}",
  },
  {
    text: "Still I Rise.",
    author: "Maya Angelou",
    role: "Poet & Civil Rights Activist",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Angelou_at_Clinton_inauguration_%28cropped%29.jpg/220px-Angelou_at_Clinton_inauguration_%28cropped%29.jpg",
    gradient: "from-orange-400 to-red-500",
    emoji: "\u{1F56A}\uFE0F",
  },
  {
    text: "Hope is the thing with feathers that perches in the soul.",
    author: "Emily Dickinson",
    role: "Poet",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Emily_Dickinson_daguerreotype_%28Amherst_College_Archives%29.jpg/220px-Emily_Dickinson_daguerreotype_%28Amherst_College_Archives%29.jpg",
    gradient: "from-lime-400 to-green-600",
    emoji: "\u{1F426}",
  },
  {
    text: "One child, one teacher, one book, one pen can change the world.",
    author: "Malala Yousafzai",
    role: "Nobel Peace Laureate",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Malala_Yousafzai_at_Girl_Summit_2014-cropped.jpg/220px-Malala_Yousafzai_at_Girl_Summit_2014-cropped.jpg",
    gradient: "from-pink-400 to-rose-600",
    emoji: "\u{1F4DD}",
  },
  {
    text: "Lose your dream, you lose your mind.",
    author: "P.V. Sindhu",
    role: "Olympic Badminton Champion",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/P.V._Sindhu_%28cropped%29.jpg/220px-P.V._Sindhu_%28cropped%29.jpg",
    gradient: "from-cyan-400 to-teal-600",
    emoji: "\u{1F3F8}",
  },
  {
    text: "In the depth of winter, I finally learned that within me there lay an invincible summer.",
    author: "Sappho",
    role: "Ancient Greek Poet",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Bust_Sappho_Musei_Capitolini_MC1164.jpg/220px-Bust_Sappho_Musei_Capitolini_MC1164.jpg",
    gradient: "from-yellow-400 to-amber-600",
    emoji: "\u{1F3DB}\uFE0F",
  },
  {
    text: "Doubt is a killer. You just have to know who you are and what you stand for.",
    author: "Mary J. Blige",
    role: "Singer & Actress",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Mary_J._Blige_2021_%28cropped%29.jpg/220px-Mary_J._Blige_2021_%28cropped%29.jpg",
    gradient: "from-purple-400 to-fuchsia-600",
    emoji: "\u{1F3A4}",
  },
];

export const statusColors: Record<string, string> = {
  'Done': 'bg-emerald-100 text-emerald-800 border-emerald-200',
  'In progress': 'bg-blue-100 text-blue-800 border-blue-200',
  'New': 'bg-purple-100 text-purple-800 border-purple-200',
  'Carried fwd': 'bg-amber-100 text-amber-800 border-amber-200',
  'Due': 'bg-red-100 text-red-800 border-red-200',
  'Scheduled': 'bg-cyan-100 text-cyan-800 border-cyan-200',
  'On hold': 'bg-gray-100 text-gray-800 border-gray-200',
};

export const statusEmoji: Record<string, string> = {
  'Done': '\u2705',
  'In progress': '\u{1F3C3}\u200D\u2640\uFE0F',
  'New': '\u2728',
  'Carried fwd': '\u{1F504}',
  'Due': '\u{1F525}',
  'Scheduled': '\u{1F4C5}',
  'On hold': '\u23F8\uFE0F',
};
