import { Task } from './types';
import { allQuotes } from './quotes';

export const initialTasks: Task[] = [
  {
    id: '1',
    owner: 'Reema',
    action: 'Meet Linda today: understand current segmentation, contact lists, newsletter workflows.',
    deadline: '9 Apr',
    deadlineDate: new Date(2026, 3, 9),
    status: 'In progress',
    subtasks: [
      { id: '1-1', title: 'Review current segmentation model', hoursRequired: 2, completed: true },
      { id: '1-2', title: 'Map contact list sources', hoursRequired: 1.5, completed: false },
      { id: '1-3', title: 'Document newsletter workflow', hoursRequired: 1, completed: false },
    ],
  },
  {
    id: '2',
    owner: 'Reema',
    action: 'Get CRM (C4/HANA) walkthrough from Jan – understand existing data structure before designing Marketing Cloud segments.',
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'New',
    subtasks: [
      { id: '2-1', title: 'Schedule walkthrough with Jan', hoursRequired: 0.5, completed: false },
      { id: '2-2', title: 'Document data fields & relationships', hoursRequired: 3, completed: false },
      { id: '2-3', title: 'Map CRM fields to Marketing Cloud', hoursRequired: 2, completed: false },
    ],
  },
  {
    id: '3',
    owner: 'Reema',
    action: 'Produce "what is currently possible" Marketing Cloud capability document after Linda meeting.',
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'New',
    subtasks: [
      { id: '3-1', title: 'Audit current Marketing Cloud features', hoursRequired: 2, completed: false },
      { id: '3-2', title: 'Draft capability document', hoursRequired: 3, completed: false },
      { id: '3-3', title: 'Review with stakeholders', hoursRequired: 1, completed: false },
    ],
  },
  {
    id: '4',
    owner: 'Reema',
    action: 'Draft Marketing Cloud segmentation architecture proposal (customer groups, countries, roles, nomenclature). Share with Jacek before kickoff.',
    deadline: 'w/c 21 Apr',
    deadlineDate: new Date(2026, 3, 21),
    status: 'New',
    subtasks: [
      { id: '4-1', title: 'Define customer group taxonomy', hoursRequired: 2, completed: false },
      { id: '4-2', title: 'Create country/role matrix', hoursRequired: 2, completed: false },
      { id: '4-3', title: 'Draft naming conventions', hoursRequired: 1, completed: false },
      { id: '4-4', title: 'Write architecture proposal', hoursRequired: 3, completed: false },
    ],
  },
  {
    id: '5',
    owner: 'Reema',
    action: 'Arrange Prodware call (with Jan + Thomas) to clarify: social connector, Query Assist, licence count, integration with CRM.',
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'Carried fwd',
    subtasks: [
      { id: '5-1', title: 'Prepare agenda and questions', hoursRequired: 1, completed: true },
      { id: '5-2', title: 'Schedule call with all parties', hoursRequired: 0.5, completed: false },
      { id: '5-3', title: 'Document findings', hoursRequired: 1.5, completed: false },
    ],
  },
  {
    id: '6',
    owner: 'Reema',
    action: 'Draft Marketing Cloud MVP proposal + target-state document.',
    deadline: 'w/c 21 Apr',
    deadlineDate: new Date(2026, 3, 21),
    status: 'Carried fwd',
    subtasks: [
      { id: '6-1', title: 'Define MVP scope', hoursRequired: 2, completed: false },
      { id: '6-2', title: 'Create target-state vision', hoursRequired: 3, completed: false },
      { id: '6-3', title: 'Write proposal document', hoursRequired: 4, completed: false },
    ],
  },
  {
    id: '7',
    owner: 'Reema',
    action: 'Identify 2-3 Indian rendering agencies (STEP-to-render) with international/German brand credentials.',
    deadline: 'Mid-Apr',
    deadlineDate: new Date(2026, 3, 15),
    status: 'Carried fwd',
    subtasks: [
      { id: '7-1', title: 'Research agencies with German brand work', hoursRequired: 3, completed: false },
      { id: '7-2', title: 'Review portfolios and pricing', hoursRequired: 2, completed: false },
      { id: '7-3', title: 'Create shortlist with recommendations', hoursRequired: 1, completed: false },
    ],
  },
  {
    id: '8',
    owner: 'Reema',
    action: "Review Gosia's HWST drive; identify specific digital support areas (landing page, social).",
    deadline: 'w/c 8 Apr',
    deadlineDate: new Date(2026, 3, 8),
    status: 'Carried fwd',
    subtasks: [
      { id: '8-1', title: 'Review all HWST drive materials', hoursRequired: 2, completed: false },
      { id: '8-2', title: 'Identify digital gaps', hoursRequired: 1.5, completed: false },
      { id: '8-3', title: 'Propose support plan', hoursRequired: 1, completed: false },
    ],
  },
  {
    id: '9',
    owner: 'Reema',
    action: 'Verify DeepL English translations of Storatherm HF 500/800 promo materials with Gosia + Linda.',
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'New',
    subtasks: [
      { id: '9-1', title: 'Run DeepL translations', hoursRequired: 1, completed: false },
      { id: '9-2', title: 'Review with Gosia', hoursRequired: 1, completed: false },
      { id: '9-3', title: 'Final review with Linda', hoursRequired: 0.5, completed: false },
    ],
  },
  {
    id: '10',
    owner: 'Reema',
    action: "Draft strategic content playbook (beyond Linda's operational plan).",
    deadline: 'Before 20 Apr',
    deadlineDate: new Date(2026, 3, 20),
    status: 'New',
    subtasks: [
      { id: '10-1', title: 'Define content pillars', hoursRequired: 2, completed: false },
      { id: '10-2', title: 'Create channel strategy', hoursRequired: 2, completed: false },
      { id: '10-3', title: 'Draft playbook document', hoursRequired: 4, completed: false },
    ],
  },
  {
    id: '11',
    owner: 'Reema',
    action: "Get own Social Hub access (currently sharing Maik's). Analyse existing content/calendar.",
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'New',
    subtasks: [
      { id: '11-1', title: 'Request Social Hub access', hoursRequired: 0.5, completed: false },
      { id: '11-2', title: 'Audit existing content calendar', hoursRequired: 2, completed: false },
    ],
  },
  {
    id: '12',
    owner: 'Reema',
    action: 'Study Schneider Electric data-centre cooling pages as benchmark.',
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'New',
    subtasks: [
      { id: '12-1', title: 'Analyse Schneider page structure', hoursRequired: 1.5, completed: false },
      { id: '12-2', title: 'Document best practices', hoursRequired: 1, completed: false },
    ],
  },
  {
    id: '13',
    owner: 'Reema',
    action: 'Rewrite Switzerland/Michele LinkedIn post – remove IMI name.',
    deadline: '8 Apr',
    deadlineDate: new Date(2026, 3, 8),
    status: 'Due',
    subtasks: [
      { id: '13-1', title: 'Rewrite LinkedIn post copy', hoursRequired: 1, completed: false },
      { id: '13-2', title: 'Get approval and publish', hoursRequired: 0.5, completed: false },
    ],
  },
  {
    id: '14',
    owner: 'Jacek',
    action: 'Define Content Engine project scope + team; organise kickoff in April.',
    deadline: 'w/c 21 Apr',
    deadlineDate: new Date(2026, 3, 21),
    status: 'New',
    subtasks: [
      { id: '14-1', title: 'Define project scope document', hoursRequired: 3, completed: false },
      { id: '14-2', title: 'Identify team members', hoursRequired: 1, completed: false },
      { id: '14-3', title: 'Schedule kickoff meeting', hoursRequired: 0.5, completed: false },
    ],
  },
  {
    id: '15',
    owner: 'Jacek',
    action: 'Request Andreas to organise 4-5 product training sessions for Reema (online, April).',
    deadline: 'w/c 8 Apr',
    deadlineDate: new Date(2026, 3, 8),
    status: 'Carried fwd',
    subtasks: [
      { id: '15-1', title: 'Contact Andreas', hoursRequired: 0.5, completed: false },
      { id: '15-2', title: 'Define training topics', hoursRequired: 1, completed: false },
    ],
  },
  {
    id: '16',
    owner: 'Jacek',
    action: 'Share Schneider Electric data-centre link with Reema (done in-chat).',
    deadline: '9 Apr',
    deadlineDate: new Date(2026, 3, 9),
    status: 'Done',
    subtasks: [
      { id: '16-1', title: 'Share link', hoursRequired: 0.1, completed: true },
    ],
  },
  {
    id: '17',
    owner: 'Jacek',
    action: 'Re-establish expired recurring team meeting (Viktor, Linda, Reema).',
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'New',
    subtasks: [
      { id: '17-1', title: 'Find available time slot', hoursRequired: 0.5, completed: false },
      { id: '17-2', title: 'Send calendar invite', hoursRequired: 0.25, completed: false },
    ],
  },
  {
    id: '18',
    owner: 'Jacek',
    action: 'Schedule 20 April content/social strategy meeting: Jacek + Reema + Linda + David.',
    deadline: '9 Apr',
    deadlineDate: new Date(2026, 3, 9),
    status: 'Done',
    subtasks: [
      { id: '18-1', title: 'Send meeting invite', hoursRequired: 0.25, completed: true },
    ],
  },
  {
    id: '19',
    owner: 'Jacek',
    action: 'Confirm Karolina as budget-file contact for Reema.',
    deadline: 'w/c 8 Apr',
    deadlineDate: new Date(2026, 3, 8),
    status: 'Carried fwd',
    subtasks: [
      { id: '19-1', title: 'Confirm with Karolina', hoursRequired: 0.25, completed: false },
    ],
  },
  {
    id: '20',
    owner: 'J + R + Gosia',
    action: 'Three-way alignment: map project responsibilities, agree contribution model.',
    deadline: 'w/c 14 Apr',
    deadlineDate: new Date(2026, 3, 14),
    status: 'Carried fwd',
    subtasks: [
      { id: '20-1', title: 'Prepare responsibility matrix', hoursRequired: 2, completed: false },
      { id: '20-2', title: 'Schedule alignment meeting', hoursRequired: 0.5, completed: false },
      { id: '20-3', title: 'Document agreed model', hoursRequired: 1, completed: false },
    ],
  },
  {
    id: '21',
    owner: 'Team',
    action: 'Content/Social Strategy meeting: social channels, Instagram consolidation, integration with Marketing Cloud.',
    deadline: '20 Apr',
    deadlineDate: new Date(2026, 3, 20),
    status: 'Scheduled',
    subtasks: [
      { id: '21-1', title: 'Prepare meeting agenda', hoursRequired: 1, completed: false },
      { id: '21-2', title: 'Compile channel audit data', hoursRequired: 2, completed: false },
      { id: '21-3', title: 'Prepare Instagram consolidation proposal', hoursRequired: 2, completed: false },
    ],
  },
  {
    id: '22',
    owner: 'Team',
    action: 'Dubai/Moustapha meeting: postponed (work-permit).',
    deadline: 'TBD',
    deadlineDate: null,
    status: 'On hold',
    subtasks: [],
  },
];

export const quotes = allQuotes;

export const statusColors: Record<string, string> = {
  'Done': 'bg-emerald-100 text-emerald-800 border-emerald-200',
  'In progress': 'bg-blue-100 text-blue-800 border-blue-200',
  'New': 'bg-purple-100 text-purple-800 border-purple-200',
  'Carried fwd': 'bg-amber-100 text-amber-800 border-amber-200',
  'Due': 'bg-red-100 text-red-800 border-red-200',
  'Scheduled': 'bg-cyan-100 text-cyan-800 border-cyan-200',
  'On hold': 'bg-gray-100 text-gray-800 border-gray-200',
};

export const statusEmoji: Record<string, string> = {
  'Done': '\u2705',
  'In progress': '\u{1F3C3}\u200D\u2640\uFE0F',
  'New': '\u2728',
  'Carried fwd': '\u{1F504}',
  'Due': '\u{1F525}',
  'Scheduled': '\u{1F4C5}',
  'On hold': '\u23F8\uFE0F',
};
